apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-config
  namespace: vpn
spec:
  storageClassName: wg-easy-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
