---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: backup
data:
  backup-weekly.sh: |-
    #!/bin/sh
    apt-get update
    apt-get install -y rsync lbzip2

    echo "#> Starting weekly rsync file sync..."
    
    echo "#> Compressing the weekly folders to a tar.bz2..."
    mkdir -p ~/tar-get/
    rm -rf ~/tar-get/* 
    
    tar -I lbzip2 -cvf ~/tar-get/weekly.tar.bz2 nextcloud-data configs mariadb plex tautulli 
    echo "Before"
    du -h -s nextcloud-data configs mariadb plex tautulli 
    echo "After"
    du -h -s ~/tar-get/weekly.tar.bz2

    echo "#> Backing up tar.bz2..."
    rsync -a --no-perms --no-owner --no-group --delete --force --update --progress ~/tar-get/ /backup/weekly/    

  backup-nightly.sh: |-
    #!/bin/sh
    apt-get update
    apt-get install -y rsync
    
    echo "#> Starting nightly rsync file sync..."
    echo "#> Backing up nextcloud..."
    rsync -a -z --no-perms --no-owner --no-group --delete --force --update --progress /nextcloud-data /backup/nightly/nextcloud    
    echo "#> Backing up configs..."
    rsync -a -z --no-perms --no-owner --no-group --delete --force --update --progress /configs /backup/nightly/configs    
    echo "#> Backing up mariadb..."
    rsync -a -z --no-perms --no-owner --no-group --delete --force --update --progress /mariadb /backup/nightly/mariadb
    echo "#> Backing up plex..."
    rsync -a -z --no-perms --no-owner --no-group --delete --force --update --progress /plex /backup/nightly/plex
    echo "#> Backing up tautulli..."
    rsync -a -z --no-perms --no-owner --no-group --delete --force --update --progress /tautulli /backup/nightly/tautulli
 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-nextcloud-data-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-nextcloud-data"
  resources:
    requests:
      storage: 800Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-configs-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-configs"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-mariadb-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-mariadb"
  resources:
    requests:
      storage: 30Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-plex-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-plex"
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-tautulli-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-tautulli"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-event-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-event"
  resources:
    requests:
      storage: 50Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-nextcloud-weekly
  namespace: backup
  labels:
    app: backup-nextcloud-weekly
spec:
  schedule: "5 2 * * 0"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backup
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - big-raver
          restartPolicy: Never    
          volumes:
          - name: nfs-backup-volume
            nfs: 
              server: 10.8.0.10 # TODO: use DNS
              path: /mnt/largehdd/backup
          - name: backup-script-volume
            configMap:
              name: backup-script
              items:
              - key: backup-weekly.sh
                path: backup-weekly.sh
              defaultMode: 0744
          - name: backup-nextcloud-data-volume
            persistentVolumeClaim:
              claimName: backup-nextcloud-data-claim
          - name: backup-configs-volume
            persistentVolumeClaim:
              claimName: backup-configs-claim
          - name: backup-mariadb-volume
            persistentVolumeClaim:
              claimName: backup-mariadb-claim
          - name: backup-plex-volume
            persistentVolumeClaim:
              claimName: backup-plex-claim
          - name: backup-tautulli-volume
            persistentVolumeClaim:
              claimName: backup-tautulli-claim
          - name: backup-event-volume
            persistentVolumeClaim:
              claimName: backup-event-claim
          containers:
          - name: backup
            image: ubuntu:latest
            resources:
              limits:
                memory: "2048Mi"
                cpu: "700m"
            command: 
              - /backup-script/backup-weekly.sh
            volumeMounts:
              - name: backup-script-volume
                mountPath: /backup-script
              - name: nfs-backup-volume
                mountPath: /backup
              - name: backup-nextcloud-data-volume
                mountPath: "/nextcloud-data"
              - name: backup-configs-volume
                mountPath: "/configs"
              - name: backup-mariadb-volume
                mountPath: "/mariadb"
              - name: backup-plex-volume
                mountPath: "/plex"
              - name: backup-tautulli-volume
                mountPath: "/tautulli"
              - name: backup-event-volume
                mountPath: "/event"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-nextcloud-nightly
  namespace: backup
  labels:
    app: backup-nextcloud-nightly
spec:
  schedule: "5 4 */2 * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backup
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - big-raver
          restartPolicy: Never    
          volumes:
          - name: nfs-backup-volume
            nfs: 
              server: 10.8.0.10 # TODO: Use DNS
              path: /mnt/largehdd/backup
          - name: backup-script-volume
            configMap:
              name: backup-script
              items:
              - key: backup-nightly.sh
                path: backup-nightly.sh
              defaultMode: 0744
          - name: backup-nextcloud-data-volume
            persistentVolumeClaim:
              claimName: backup-nextcloud-data-claim
          - name: backup-configs-volume
            persistentVolumeClaim:
              claimName: backup-configs-claim
          - name: backup-mariadb-volume
            persistentVolumeClaim:
              claimName: backup-mariadb-claim
          - name: backup-plex-volume
            persistentVolumeClaim:
              claimName: backup-plex-claim
          - name: backup-tautulli-volume
            persistentVolumeClaim:
              claimName: backup-tautulli-claim
          - name: backup-event-volume
            persistentVolumeClaim:
              claimName: backup-event-claim
          containers:
          - name: backup
            image: ubuntu:latest
            resources:
              limits:
                memory: "2048Mi"
                cpu: "700m"
            command: 
              - /backup-script/backup-nightly.sh
            volumeMounts:
              - name: backup-script-volume
                mountPath: /backup-script
              - name: nfs-backup-volume
                mountPath: /backup
              - name: backup-nextcloud-data-volume
                mountPath: "/nextcloud-data"
              - name: backup-configs-volume
                mountPath: "/configs"
              - name: backup-mariadb-volume
                mountPath: "/mariadb"
              - name: backup-plex-volume
                mountPath: "/plex"
              - name: backup-tautulli-volume
                mountPath: "/tautulli"
              - name: backup-event-volume
                mountPath: "/event"