---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-storage-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-storage"
  resources:
    requests:
      storage: 2000Gi
