---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-nextcloud-data-pv
  labels:
    contenttype: "backup-nextcloud-data"
spec:
  capacity:
    storage: 800Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largehdd/nextcloud-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-nextcloud-web-pv
  labels:
    contenttype: "backup-nextcloud-web"
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largessd/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-configs-pv
  labels:
    contenttype: "backup-configs"
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largessd/configs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-mariadb-pv
  labels:
    contenttype: "backup-mariadb"
spec:
  capacity:
    storage: 30Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largehdd/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-plex-pv
  labels:
    contenttype: "backup-plex"
spec:
  capacity:
    storage: 20Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largehdd/plex
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-tautulli-pv
  labels:
    contenttype: "backup-tautulli"
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largehdd/tautulli
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-finance-pv
  labels:
    contenttype: "backup-finance"
spec:
  capacity:
    storage: 50Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largehdd/finance
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup-event-pv
  labels:
    contenttype: "backup-event"
spec:
  capacity:
    storage: 50Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largehdd/event
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
