---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-storage-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-storage"
  resources:
    requests:
      storage: 2000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-nextcloud-data-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-nextcloud-data"
  resources:
    requests:
      storage: 800Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-nextcloud-web-claim
  namespace: backup
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "backup-nextcloud-web"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: backup
  labels:
    app: backup
spec:
  schedule: "0 4 * * 0,3"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backup
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - big-raver
          restartPolicy: Never    
          volumes:
          - name: backup-script-volume
            configMap:
              name: backup-script
              items:
              - key: backup.sh
                path: backup.sh
              defaultMode: 0744
          - name: backup-storage-volume
            persistentVolumeClaim:
              claimName: backup-storage-claim
          - name: backup-nextcloud-data-volume
            persistentVolumeClaim:
              claimName: backup-nextcloud-data-claim
          - name: backup-nextcloud-web-volume
            persistentVolumeClaim:
              claimName: backup-nextcloud-web-claim
          containers:
          - name: backup
            image: instrumentisto/rsync-ssh
            command: 
              - /backup-script/backup.sh
            volumeMounts:
              - name: backup-script-volume
                mountPath: /backup-script
              - name: backup-storage-volume
                mountPath: /backup
              - name: backup-nextcloud-data-volume
                mountPath: "/nextcloud-data"
              - name: backup-nextcloud-web-volume
                mountPath: "/nextcloud-web"