apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ubuntu-xfce4.yml
  - middleware.yml
  - auth-middleware.yml
configMapGenerator:
- name: ubuntu-xfce4-init
  files:
  - init.sh
generatorOptions:
  disableNameSuffixHash: true
