apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ubuntu-xfce4.yml
  - middleware.yml
  - auth-middleware.yml
  - container-build.yml
configMapGenerator:
- name: ubuntu-xfce4-init
  files:
  - init.sh
- name: ubuntu-xfce4-dockerfile
  files:
  - Dockerfile
- name: ubuntu-xfce4-install-tools
  files:
  - ../common/install-tools.sh
generatorOptions:
  disableNameSuffixHash: true
