apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-xfce4
  namespace: development
  labels:
    app: ubuntu-xfce4
    sablier.enable: "true"
    sablier.group: ubuntu-xfce4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-xfce4
  template:
    metadata:
      labels:
        task: development
        app: ubuntu-xfce4
    spec:
      priorityClassName: development-priority
      containers:
      - name: ubuntu-xfce4
        image: registry.registry.svc.cluster.local:5000/ubuntu-xfce4:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6080
          name: novnc
        - containerPort: 5900
          name: vnc
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
        - name: DISPLAY
          value: ":1"
        - name: RESOLUTION
          value: "1280x800x24"
        - name: HOME
          value: "/home/basraven"
        command: ["/bin/sh", "-c"]
        args:
        - /init.sh
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "4000m"
        volumeMounts:
        - name: openvscode-server-home-volume
          mountPath: /home
        - name: dev-shm
          mountPath: /dev/shm
        - name: ubuntu-xfce4-init
          mountPath: /init.sh
          subPath: init.sh
        - name: install-tools
          mountPath: /install-tools.sh
          subPath: install-tools.sh
        - name: vnc-auth
          mountPath: /etc/vnc-auth
          readOnly: true
      volumes:
      - name: openvscode-server-home-volume
        persistentVolumeClaim:
          claimName: openvscode-server-home-claim
      - name: dev-shm
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi
      - name: ubuntu-xfce4-init
        configMap:
          name: ubuntu-xfce4-init
          items:
          - key: init.sh
            path: init.sh
          defaultMode: 0755
      - name: install-tools
        configMap:
          name: install-tools
          items:
          - key: install-tools.sh
            path: install-tools.sh
          defaultMode: 0755
      - name: vnc-auth
        secret:
          secretName: ubuntu-xfce4-vnc-auth
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-xfce4
  namespace: development
spec:
  ports:
  - port: 80
    targetPort: 6080
    name: novnc
  - port: 5900
    targetPort: 5900
    name: vnc
  selector:
    app: ubuntu-xfce4
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ubuntu-xfce4-bas
  namespace: development
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: ubuntu-xfce4-bas-tls
  commonName: ubuntu.bas
  dnsNames:
  - ubuntu.bas
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-xfce4-vnc-lb
  namespace: development
spec:
  type: LoadBalancer
  # Requires manual add of vnc.ubuntu.bas in pihole.bas
  loadBalancerIP: 192.168.6.31
  ports:
  - port: 5900
    targetPort: 5900
    name: vnc
  selector:
    app: ubuntu-xfce4
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuntu-xfce4-https
  namespace: development
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "development-authentik-ubuntu-xfce4@kubernetescrd,development-sablier-ubuntu-xfce4@kubernetescrd"
spec:
  tls:
  - secretName: ubuntu-xfce4-bas-tls
  rules:
  - host: ubuntu.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ubuntu-xfce4
            port:
              number: 80
