---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glacier-workingdir-claim
spec:
  storageClassName: glacier-workingdir
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi