---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-ro-glacier-claim
spec:
  storageClassName: hdd-ro-glacier
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
