apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv
  - system-audit.yml
  - middleware.yml
configMapGenerator:
  - name: system-audit-config
    files:
      - config/requirements.txt
      - config/checks.yaml
      - config/app.py
      - config/audit.py
