---
# Source: sparkoperator/templates/spark-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: 
    sparkacount
  namespace: spark-jobs
  labels:
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.6.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
