---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web
  namespace: analytics
  labels:
    app: cassandra-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-web
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
      - name: cassandra-web
        image: basraven/cassandra-web
        resources:
          requests:
           cpu: "50m"
           memory: 56Mi
          limits:
            cpu: "200m"
            memory: 256Mi
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: CASSANDRA_HOST
          value: cassandra
        - name: CASSANDRA_PORT
          value: "9042"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-web
  name: cassandra-web
  namespace: analytics
spec:
  ports:
  - name: http
    targetPort: 3000
    port: 80
  selector:
    app: cassandra-web
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cassandrawebingress
  namespace: analytics
spec:
  rules:
  - host: cassandra.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cassandra-web
            port:
              number: 80