---
apiVersion: backup.la1r.com/v1
kind: cloudbackup
metadata:
  name: cloudbackup-media
spec:
  cloud:
    type: s3-deeparchive
    bucket: la1r-cloud-backup
    region: us-east-1
    prefix: media/
  compression: 
    # type: tar
    # arguments: -cf
    type: 7zip
    arguments: -m0=lzma2 -mx=9
  encryption:
    type: gpg
  sources:
    - name: "media"
      path: "/s3-backup/media"
      target: "/s3-backup/tmp/media"
      excludes:
      - skipme
    # - name: "stephanie"
    #   path: "/mnt/hdd/media/stephanie"
    #   target: "stephanie/"
    #   excludes:
    # - name: "gezin"
    #   path: "/mnt/hdd/media/gezin"
    #   target: "gezin/"
    #   excludes:

