---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: torrent
  labels:
    app: radarr
    sablier.enable: "true"
    sablier.group: jellyfin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"
      volumes:
        - name: radarr-config-volume
          persistentVolumeClaim:
            claimName: radarr-config-claim
        - name: radarr-torrent-volume
          persistentVolumeClaim:
            claimName: radarr-torrent-data-claim
      containers:
      - name: radarr
        resources:
        image: linuxserver/radarr
        ports:
        - name: http
          containerPort: 7878
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: radarr-config-volume
            mountPath: /config
          - name: radarr-torrent-volume
            mountPath: /downloads
       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 7878
    port: 80
  selector:
    app: radarr
  type: ClusterIP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-bas
  namespace: torrent
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: radarr-bas-tls
  commonName: radarr.bas
  dnsNames:
  - radarr.bas
  - www.radarr.bas
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-https
  namespace: torrent
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "torrent-sablier-radarr@kubernetescrd"
spec:
  tls:
  - secretName: radarr-bas-tls
  rules:
  - host: radarr.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80