---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: otbr-config-pv
  labels:
    contenttype: "otbr-config"
spec:
  capacity:
    storage: 100Mi
  storageClassName: otbr-config
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/homeassistant/otbr"
