---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-config-claim
  namespace: homeautomation
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: z2m-config
  selector:
    matchLabels:
      contenttype: "z2m-config"
  resources:
    requests:
      storage: 1Gi
