apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: homeautomation
data:
  mosquitto.conf: |
    # mosquitto.conf
    # Change the port to 1883
    listener 1883

    # Allow anonymous access
    allow_anonymous true

    # Disable persistence
    persistence false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: homeautomation
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      
      # specificonly only workloads
      tolerations:
        - key: "la1r.workload/specificonly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "la1r.workload/specificonly"
                operator: "In"
                values:
                - "true"

      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        # - name: mqtt-data-volume
        #   persistentVolumeClaim:
        #     claimName: mqtt-data-claim
      containers:
      - name: mqtt
        image: eclipse-mosquitto:latest
        ports:
        - name: http
          containerPort: 1883
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        # - name: mqtt-data-volume
        #   mountPath: /mosquitto/data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt
  name: mqtt
  namespace: homeautomation
spec:
  ports:
  - name: http
    port: 1883
    targetPort: 1883
  selector:
    app: mqtt
  type: ClusterIP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: mqtt-lb
#   name: mqtt-lb
#   namespace: homeautomation
# spec:
#   ports:
#   - name: http
#     targetPort: 1883
#     port: 80
#   selector:
#     app: mqtt
#   loadBalancerIP: 192.168.6.78
#   type: LoadBalancer

# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-mqtt
#   namespace: homeautomation
# spec:
#   podSelector: {}  # Selects all pods in the namespace
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - {}
#   egress:
#   - {}
  # podSelector:
  #   matchLabels:
  #     app: mqtt
  # ingress:
  # - from:
  #   - podSelector: {}  # Allow traffic from any pod
  #   ports:
  #   - protocol: TCP
  #     port: 1883
  # egress:
  # - to:
  #   - podSelector: {}  # Allow traffic to any pod
  #   ports:
  #   - protocol: TCP
  #     port: 1883
  # policyTypes:
  # - Ingress
  # - Egress
