kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- 
  role: control-plane
  extraPortMappings:
  - containerPort: 31300
    hostPort: 31300
  - containerPort: 31301
    hostPort: 31301
  - containerPort: 31302
    hostPort: 31302
  - containerPort: 31303
    hostPort: 31303
  - containerPort: 31304
    hostPort: 31304
  - containerPort: 31305
    hostPort: 31305
  - containerPort: 31306
    hostPort: 31306
  - containerPort: 31307
    hostPort: 31307
- role: control-plane
