---
- hosts: all
  remote_user: basraven
  tasks:
    - name: Add the user backup with a specific uid and a primary group of 'backup'
      user:
        name: backup
        shell: /bin/bash
        home: /home/backup
        groups: backup
        uid: 1040
        append: yes
    - name: Set authorized key took from file
      authorized_key:
        user: backup
        key: "{{ lookup('file', '/credentials/ssh/backup/id_rsa.pub') }}"
        state: present
