---
- hosts: all
  remote_user: pi
  tasks:
    - name: Add the user '{{target_user}}' with a specific uid and a primary group of 'sudo'
      user:
        name: "{{target_user}}"
        shell: /bin/bash
        groups: sudo,adm,dialout,cdrom,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
        append: yes
    - name: Add {{ target_user }} user to the sudoers
      copy:
          dest: "/etc/sudoers.d/{{ target_user }}"
          content: "{{ target_user }}  ALL=(ALL)  NOPASSWD: ALL"
    - name: Set authorized key took from file
      authorized_key:
        user: "{{target_user}}"
        key: "{{ lookup('file', '/credentials/ssh/id_rsa.pub') }}"
        state: present
    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes
      notify:
        - restart ssh
    - name: Disable Root Login
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin no"
        state=present
        backup=yes
      notify:
        - restart ssh

    # FIXME: contains an error
    - name: Set hostname of Raspberry pi to the hostname marked on the inventory file
      shell: raspi-config nonint do_hostname {{  inventory_hostname }}''
      args:
          executable: /bin/bash
    - name: Install OpenVPN, Easy-rsa, UFW and Fail2ban
      apt: name={{item}} state=present
      with_items:
        - ufw
        - fail2ban
    - name: Enable UFW ports
      shell: 'ufw allow ssh ; ufw limit ssh/tcp ; ufw enable'
      args:
          executable: /bin/bash
    - name: Copy jail file
      shell: 'cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local'
      args:
          executable: /bin/bash
  handlers:
    - name: restart ssh
      service:
        name=ssh
        state=restarted