---
- hosts: all
  remote_user: {{target_user}}
  tasks:
  - name: "Set '/etc/os-release'"
    copy:
      src: os-release
      dest: /etc/os-release
    tags: [docker]
    become: True
  # - name: Install required packages 
  #   apt: name={{item}} state=installed
  #   with_items:
  #       - lsb-core
  #   become: True
  # - name: Update and upgrade apt packages
  #   apt:
  #     upgrade: yes
  #     update_cache: yes
  #     cache_valid_time: 86400 #One day
  #   become: true