---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes
    - name: Enable pubkey Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PubkeyAuthentication'
        line="PubkeyAuthentication yes"
        state=present
        backup=yes
    - name: Disable Root Login
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line="PermitRootLogin no"
        state=present
        backup=yes
      notify:
        - restart ssh
    - name: Include root credentials
      include_vars:
        file: "{{credentials_dir}}/root/root-credentials.yaml"
    - name: Change root pw
      shell: 'echo -e "{{root_password}}\n{{root_password}}" | passwd {{ target_user }}'
      args:
          executable: /bin/bash

    # FIXME: contains an error
    - name: Set hostname of Raspberry pi to the hostname marked on the inventory file
      shell: raspi-config nonint do_hostname {{  inventory_hostname }}''
      args:
          executable: /bin/bash
    - name: Install UFW and Fail2ban
      apt: name={{item}} state=present
      with_items:
        - ufw
        - fail2ban
    - name: Enable UFW ports
      shell: 'ufw allow ssh ; ufw limit ssh/tcp ; ufw enable'
      args:
          executable: /bin/bash
    - name: Copy jail file
      shell: 'cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local'
      args:
          executable: /bin/bash
  handlers:
    - name: restart ssh
      service:
        name=ssh
        state=restarted