---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: torrent
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      priorityClassName: torrent-priority
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"

      volumes:
        - name: sonarr-config-volume
          persistentVolumeClaim:
            claimName: sonarr-config-claim
        - name: sonarr-torrent-volume
          persistentVolumeClaim:
            claimName: sonarr-torrent-data-claim
        - name: sonarr-torrent-ssd-volume
          persistentVolumeClaim:
            claimName: sonarr-torrent-ssd-data-claim
      containers:
      - name: sonarr
        resources:
        image: linuxserver/sonarr
        ports:
        - name: http
          containerPort: 8989
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: sonarr-config-volume
            mountPath: /config
          - name: sonarr-torrent-volume
            mountPath: /torrent
          - name: sonarr-torrent-ssd-volume
            mountPath: /torrent-ssd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 8989
    port: 80
  selector:
    app: sonarr
  type: ClusterIP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-bas
  namespace: torrent
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: sonarr-bas-tls
  commonName: sonarr.bas
  dnsNames:
  - sonarr.bas
  - www.sonarr.bas
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-https
  namespace: torrent
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  tls:
  - secretName: sonarr-bas-tls
  rules:
  - host: sonarr.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 80