---
nfs_server_address: "10.8.0.18"

nfs_storage_classes:
  111:
    hostpath: "/mnt/ssd/ha"
  211:
    hostpath: "/mnt/ssd/na"
  221:
    hostpath: "/mnt/ssd/tmp"
  112:
    hostpath: "/mnt/hdd/ha"
  212:
    hostpath: "/mnt/hdd/na"
  222:
    hostpath: "/mnt/hdd/tmp"