---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
  name: spark-service
  namespace: analytics
spec:
  ports:
  - name: http
    targetPort: 4040
    port: 80
  selector:
    interpreterGroupId: spark-shared_process
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ingress
  namespace: analytics
spec:
  rules:
  - host: spark.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spark-service
            port:
              number: 80
