---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-workingdir-claim
spec:
  storageClassName: vaultwarden-workingdir
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
