---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vaultwarden-ro-pv
  labels:
    contenttype: "vaultwarden-ro"
spec:
  capacity:
    storage: 1Gi
  storageClassName: vaultwarden-ro
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/ha/vaultwarden/data"

  # Essential
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: la1r.workload/essential
              operator: In
              values:
                - "true"