---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-ro-claim
spec:
  storageClassName: vaultwarden-ro
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
