---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-claim
  namespace: monitoring
spec:
  storageClassName: grafana-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
