---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: online
data:
  default.conf: |-
    server {
        listen       80;
        server_name localhost;
        # server_name  cloud.basraven.nl www.cloud.basraven.nl;
        # access_log   logs/cloud.basraven.access.log  main;

        # serve static files
        # location ~ ^/(images|javascript|js|css|flash|media|static)/  {
        #   root    /var/www/virtual/cloud.basraven.nl/htdocs;
        #   expires 30d;
        # }


        set $my_host $http_host;
        if ($http_host = "cloud.basraven.nl") {
          set $my_host "cloud.bas";
        }
          
        # http://cloud.bas/index.php/s/bYCzAd5tmpcjmnR
        # pass requests for dynamic content to rails/turbogears/zope, et al
        location / {
          return 444;
          deny all;
        }
        
        location ~ ^/index.php/s/ {
          proxy_bind      $server_addr;
          proxy_pass      http://nextcloud.nextcloud:80;
          proxy_set_header Host $my_host;
        }

        # location /index.php/s {
        #   proxy_pass      http://nextcloud.nextcloud:80;
        #   proxy_set_header Host $my_host;
        # }

        #charset koi8-r;
        # access_log  /var/log/nginx/host.access.log  main;

        # location / {
        #     root   /usr/share/nginx/html;
        #     index  index.html index.htm;
        # }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: online
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
          defaultMode: 0600
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: online
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: nginx
  type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: nginx-deny-egress
#   namespace: online
# spec:
#   podSelector:
#     matchLabels:
#       app: nginx
#   policyTypes:
#   - Egress
#   egress: []
# ---

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: online
  labels:
    expose: "online"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`cloud.basraven.nl`)
    kind: Rule
    services:
    - name: nginx
      port: 80
  tls:
    certResolver: default