---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  set-nextcloud.sh: |-
    #!/bin/sh
    set -eu
    # TODO: Put this is a new container instead of this...
    echo "[Raven] Tuning the container..."
    echo "alias www-data='su -l www-data -s /bin/bash'" >> ~/.bashrc
    #echo ''alias scanall='su -l www-data -s /bin/bash -c "PHP_MEMORY_LIMIT=512M /var/www/html/occ files:scan --all"' '' >> ~/.bashrc
    #apt-get update
    # apt-get install cron -y
    # echo "" >> /etc/crontab
    # echo "*/15  *  *  *  * www-data php -f /var/www/html/cron.php" >> /etc/crontab
    # echo "*/10  *  *  *  * www-data /var/www/html/occ preview:pre-generate" >> /etc/crontab

    # TODO: Run this:
    # /var/www/html/occ files:scan --all
    # /var/www/html/occ preview:generate-all
    # /var/www/html/occ twofactorauth:enforce --on
    # service cron start
    a2enmod http2
    a2enmod ssl
    echo "Protocols h2 h2c http/1.1" >> /etc/apache2/apache2.conf
    echo "[Raven] Done tuning the container"
    /entrypoint.sh apache2-foreground

  apcu.config: |-
    <?php
    $CONFIG = array (
      'memcache.local' => '\OC\Memcache\Redis',
      'redis' => array(
        'host' => 'redis',
        'port' => 6379,
        ),
      'memcache.locking' => '\OC\Memcache\Redis',
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution :
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"
      volumes:
      - name: set-nextcloud-volume
        configMap:
          name: nextcloud-config
          items:
          - key: set-nextcloud.sh
            path: set-nextcloud.sh
          defaultMode: 0744
      - name: apcu-config-volume
        configMap:
          name: nextcloud-config
          items:
          - key: apcu.config
            path: apcu.config
          defaultMode: 0744
      
      - name: nextcloud-web
        persistentVolumeClaim:
          claimName: nextcloud-web-claim
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-claim
      containers:
      - name: nextcloud
        image: nextcloud:24.0.2-apache
        # command:
        #   - "/set-nextcloud/set-nextcloud.sh"
        ports:
        - containerPort: 80
        resources:
        env:
        - name: REDIS_HOST
          value: "redis.nextcloud.svc.cluster.local"
        - name: OVERWRITECLIURL
          value: "https://nextcloud.bas"
        - name: OVERWRITEPROTOCOL
          value: "https"
        # - name: NEXTCLOUD_TABLE_PREFIX
        #   value: ""
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: MYSQL_HOST
          value: "mariadb.nextcloud.svc.cluster.local"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: MYSQL_PASSWORD
        - name: NEXTCLOUD_ADMIN_USER
          value: "basraven"
          # valueFrom:
          #   secretKeyRef:
          #     name: mariadbsecret
          #     key: MYSQL_USER
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: MYSQL_PASSWORD
        - name: NEXTCLOUD_TRUSTED_DOMAINS 
          value: "cloud.bas" 
        volumeMounts:
          - name: nextcloud-web
            mountPath: "/var/www/html"
          - name: nextcloud-data
            mountPath: "/var/www/html/data"
          # - name: set-nextcloud-volume
          #   mountPath: /set-nextcloud
          # - name: apcu-config-volume
          #   mountPath: /var/www/html/config
          #   subPath: apcu.config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nextcloud
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-bas
  namespace: nextcloud
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: nextcloud-bas-tls
  commonName: nextcloud.bas
  dnsNames:
  - cloud.bas
  - www.cloud.bas
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-https
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  tls:
  - secretName: nextcloud-bas-tls
  rules:
  - host: cloud.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-http
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-http-redirect-to-https@kubernetescrd"
spec:
  rules:
  - host: cloud.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80

