
# Source:   https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes
# Source 2: https://blog.ptrk.io/how-to-deploy-an-efk-stack-to-kubernetes/
---
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: monitoring
kind: ConfigMap
data:
  fluent.conf: |-
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag "#{ENV['FLUENT_CONTAINER_TAIL_TAG'] || 'kubernetes.*'}"
      exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<flags>[^ ]+) (?<message>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
    </filter>

        
    <source>
      @type tail
      <parse>
        @type multiline
        multiline_flush_interval 5s
        format_firstline /^\w+\s*\d{2}\s*\d{2}:\d{2}:\d{2}\s\w+/
        format1 /^(?<message>.*)/
      </parse>
      path /var/log/messages
      pos_file var.log.messages.pos
      path_key tailed_path
      tag omc.var.log.messages
    </source>


    <match **>
      type elasticsearch   
      log_level info
      include_tag_key true
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      # index_name fluentd.${tag}.%Y%m%d
      # logstash_prefix fluentd
      user admin
      password admin
      logstash_format true
      buffer_chunk_limit 2M
      buffer_queue_limit 32
      flush_interval 5s
      max_retry_wait 30
      disable_retry_limit
      num_threads 8
    </match>
  kubernetes.conf: |-
    <match fluent.**>
      type null
    </match>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        ports:
        - containerPort: 514
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch.monitoring"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        - name: FLUENT_UID
          value: "0"
        - name: FLUENTD_SYSTEMD_CONF
          value: "disable"
        # - name: FLUENTD_ARGS
        #   value: "--no-supervisor -q"
        # - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
        #   value: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
        - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
          value: '["/var/log/containers/fluentd*"]'
        # TODO: Test Syslog server
        # - name:  SYSLOG_HOST
        #   value: "sysloghost"
        # - name:  SYSLOG_PORT
        #   value: "514"
        # - name:  SYSLOG_PROTOCOL
        #   value: "udp"    
        image: fluent/fluentd-kubernetes-daemonset:v1.11-debian-elasticsearch7-1
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: fluentd-config-volume
            mountPath: /fluentd/etc
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config-volume
        configMap:
          name: fluentd-config

  

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-fluentd-lb-service
  namespace: monitoring
spec:
  ports:
  - name: udp
    port: 514
    targetPort: 514
  selector:
    app: fluentd
  type: LoadBalancer
  loadBalancerIP: 192.168.6.77