---
# Source:   https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes
# Source 2: https://blog.ptrk.io/how-to-deploy-an-efk-stack-to-kubernetes/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        # ports:
        # - containerPort: 24224 
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch.monitoring"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        - name: FLUENT_UID
          value: "0"
        - name: FLUENTD_SYSTEMD_CONF
          value: "disable"
        image: fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-elasticsearch7-1.0
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     task: efk
#     kubernetes.io/cluster-service: 'true'
#     kubernetes.io/name: fluentd
#   name: fluentd
#   namespace: monitoring
# spec:
#   ports:
#   - port: 80
#     targetPort: 24224
#   selector:
#     k8s-app: fluentd
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: fluentd
#   namespace: monitoring
# spec:
#   rules:
#   - host: fluentd.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: fluentd
#           servicePort: 80