---
- name: Switch server / place switch-server.py
  become: yes
  template:
    src: switch-server.py.j2
    dest: /home/basraven/switch-server.py
    mode: "0775"

- name: Switch server / place rpi_hardware_pwm.py
  become: yes
  template:
    src: rpi_hardware_pwm.py.j2
    dest: /home/basraven/rpi_hardware_pwm.py
    mode: "0775"

- name: Switch server / Enable hardware PmW
  become: yes
  lineinfile:
    path: /boot/firmware/config.txt
    line: 'dtoverlay=pwm-2chan'
    create: yes

- name: Switch server / Update apt
  become: yes
  apt:
        update_cache: yes
- name: Switch server / Install RPIO Python package using apt
  become: yes
  apt:
    name: python3-rpi.gpio
    state: present

- name: Switch server / add crontab
  become: yes
  ansible.builtin.cron:
    name: "Switch server at reboot"
    special_time: reboot
    user: root
    job: "/usr/bin/python3 /home/basraven/switch-server.py >> /var/log/switch-server.log 2>&1"