---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: openproject-config-pv
  labels:
    contenttype: "openproject-config"
spec:
  capacity:
    storage: 10Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/openproject
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - linux-wayne