apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: simple-dag
  namespace: workflows
spec:
  entrypoint: dag-example
  archiveLocation:
      archiveLogs: true
  templates:
    - name: dag-example
      dag:
        tasks:
          - name: step-1
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "Step 1: Start"
          - name: step-2
            dependencies: [step-1]
            template: bash-task
          - name: step-3
            dependencies: [step-1]
            template: python-task
          - name: step-4
            dependencies: [step-2, step-3]
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "Step 4: Done"

    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine
        command: [sh, -c]
        args: ["echo {{inputs.parameters.message}}"]

    - name: bash-task
      container:
        image: bash
        command: ["bash", "-c"]
        args: ["echo 'Step 2: Bash is running'; sleep 2"]

    - name: python-task
      container:
        image: python:3.9
        command: ["python", "-c"]
        args: ["print('Step 3: Python is running')"]
