---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-linux-wayne
  namespace: default
  labels:
    app: nginx-linux-wayne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-linux-wayne
  template:
    metadata:
      labels:
        app: nginx-linux-wayne
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution :
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - linux-wayne
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-jay-c
  namespace: default
  labels:
    app: nginx-jay-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-jay-c
  template:
    metadata:
      labels:
        app: nginx-jay-c
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution :
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - jay-c
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-linux-wayne
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-linux-wayne
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-jay-c
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-jay-c