apiVersion: kustomize.config.k8s.io/v1beta1
namespace: traefik
kind: Kustomization
namespace: traefik
resources:
  - namespace.yml
  - traefik-crd1.yml
  - traefik.yml
  - traefik-rbac.yml
  - auth-middleware.yml
  - sablier