groups:
  - name: server_target_state_jay-c
    interval: 30s  # How often the rules are evaluated

    # Recording rules (precompute metrics)
    rules:
      - record: server:target:state
        
        
        expr: |
          # 1. HTTPS DNS endpoint for past 15 mins
          SUM(increase(traefik_router_requests_total{router=~".*jellyfin.*"}[15m]))
          +
          # 2. HTTP IP endpoint for past 15 mins
          SUM(increase(traefik_entrypoint_requests_total{entrypoint="jellyfin"}[15m]))
          # +
          # # 3. Samba open sessions for past 15 mins
          # SUM(max_over_time(haproxy_frontend_current_sessions{proxy="samba_jayc_fe"}[15m]) )
          +
          # 4. Jay-C Server is already online for past 15 mins
          SUM(1 - max_over_time(probe_success{nodeName="jay-c"}[15m]))
      
      - alert: Jay-C Server should be online
        expr: server:target:state > 1
        # for: 2m
        labels:
          severity: normal
          alertname: jayc-server-offline
        annotations:
          summary: "Jay-C Server should be online but is not"
          description: "The Jay-C Server should be online but is not"    