---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: cicd
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul
        ports:
        - name: webui
          containerPort: 8500
        - name: udp
          containerPort: 8600
          protocol: UDP
        env:
          - name: "CONSUL_BIND_INTERFACE"
            value: "eth0"
        args:
          - agent
          - -server
          - -ui
          - -node=server-1
          - -bootstrap-expect=1
          - -client=0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: consul
  namespace: cicd
spec:
  ports:
  - name: webui
    targetPort: 8500
    port: 80
  - name: udp
    targetPort: 8600
    port: 8600
    protocol: UDP
  selector:
    app: consul
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul
  namespace: cicd
spec:
  rules:
  - host: consul.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: consul
          servicePort: 80 