---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data-pv
  labels:
    contenttype: "pihole-data"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: pihole-data
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/ha/pihole/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-pv
  labels:
    contenttype: "pihole-dnsmasq"
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: pihole-dnsmasq
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/ssd/ha/pihole/dnsmasq"