---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: influx-logs
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-init
  namespace: monitoring
data:
  heapster-init.iql: CREATE RETENTION POLICY "default" ON "k8s" DURATION 1d REPLICATION 1 DEFAULT;
  varken-init.iql: CREATE DATABASE varken;
  traefik-init.iql: CREATE DATABASE traefik;
  online-traefik-init.iql: CREATE DATABASE onlinetraefik;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: monitoring-influxdb
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: monitoring-influxdb
    spec:
      containers:
      - name: influxdb
        ports:
        - containerPort: 8086
        image: influxdb
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - name: influxdb-init
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: INFLUXDB_DB
            value: k8s
          - name: INFLUXDB_USER
            value: bas
          - name: INFLUXDB_USER_PASSWORD
            value: Example1
      volumes:
      - name: influxdb-init
        configMap:
          name: influxdb-init
          defaultMode: 0755
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influx-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 8086
  selector:
    k8s-app: monitoring-influxdb
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: monitoring-influxdb
#   namespace: monitoring
# spec:
#   rules:
#   - host: monitoring-influxdb.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: monitoring-influxdb
#           servicePort: 80