# ON PI4 RUN THIS FIRST:
# update-alternatives --set iptables /usr/sbin/iptables-legacy

# Source: https://docs.projectcalico.org/manifests/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: tigera-operator
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    nodeAddressAutodetectionV4:
      # interface: "e.*" # enp or eth
      skipInterface: "tun.*"
    ipPools:
    - blockSize: 26 
      cidr: 10.244.0.0/16
      encapsulation: VXLANCrossSubnet
      # encapsulation: IPIPCrossSubnet
      # ipipMode: Always
      natOutgoing: Enabled
      nodeSelector: all()
  # Configures typhaRemoval on ARM
  # typhaAffinity: 
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: kubernetes.io/arch
  #           operator: In
  #           values:
  #           - amd64
          # - key: kubernetes.io/arch
          #   operator: NotIn
          #   values:
          #   - arm
---

# This section configures the Calico API server.
# For more information, see: https://docs.projectcalico.org/v3.20/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
  namespace: tigera-operator
spec: {}