# Source: https://docs.projectcalico.org/manifests/custom-resources.yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: tigera-operator
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    nodeAddressAutodetectionV4:
      # interface: "enp.*"
      skipInterface: "tun.*"
    ipPools:
    - blockSize: 26 
      cidr: 10.244.0.0/16
      encapsulation: VXLANCrossSubnet
      # encapsulation: IPIPCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
