---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: radarr-config-data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-torrent-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: radarr-torrent-data
  resources:
    requests:
      storage: 10Gi
      