---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-traefik-config-claim
  namespace: online
spec:
  storageClassName: traefik-online-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi