apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: traefik
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: example-com-tls
  commonName: example.com
  dnsNames:
  - example.com
  - www.example.com