---
apiVersion: backup.la1r.com/v1
kind: cloudbackup
metadata:
  name: cloudbackup-media
spec:
  cloud:
    type: s3-deeparchive
    bucket: la1r-cloud-backup
    region: us-east-1
    prefix: media/
    compression: 
      type: 7zip
      arguments: -m0=lzma2 -mx=9
    encryption:
      type: gpg
  sources:
    - name: "media"
      path: "/home/basraven/Projects/la1r/kubernetes/backup/cloud-backup/media"
      target: "/home/basraven/Projects/la1r/kubernetes/backup/cloud-backup/media-zipped"
      excludes:
      - media/top_18845/folder_24764not
      - media/top_not_14594
      - media/top_not_existing_folder
      - media/top_14594/folder_23767/folder_32629/folder_13071_not
    # - name: "stephanie"
    #   path: "/mnt/hdd/media/stephanie"
    #   target: "stephanie/"
    #   excludes:
    # - name: "gezin"
    #   path: "/mnt/hdd/media/gezin"
    #   target: "gezin/"
    #   excludes:

