---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-conf-pv
  labels:
    contenttype: "nifi-conf"
spec:
  capacity:
    storage: 20Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/nifi/conf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-state-pv
  labels:
    contenttype: "nifi-state"
spec:
  capacity:
    storage: 20Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/nifi/state
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-database-repository-pv
  labels:
    contenttype: "nifi-database-repository"
spec:
  capacity:
    storage: 20Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/nifi/database-repository
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-flowfile-repository-pv
  labels:
    contenttype: "nifi-flowfile-repository"
spec:
  capacity:
    storage: 20Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/nifi/flowfile-repository
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-content-repository-pv
  labels:
    contenttype: "nifi-content-repository"
spec:
  capacity:
    storage: 20Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/nifi/content-repository
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nifi-provenance-repository-pv
  labels:
    contenttype: "nifi-provenance-repository"
spec:
  capacity:
    storage: 20Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/nifi/provenance-repository
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver