---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: flux-discord-webhook
    
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  summary: "Flux alert"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
  exclusionList:
    - "**kustomization/flux-system.flux-system**\nCustomResourceDefinition/bgppeers.metallb.io configured Installation/default configured"
    # Backup patterns in case the message format varies
    - "kustomization/flux-system.flux-system*CustomResourceDefinition/bgppeers.metallb.io configured Installation/default configured"
    - "*flux-system*CustomResourceDefinition/bgppeers.metallb.io configured*"
    - "*Installation/default configured*"
    # - github.com/metallb/metallb/config/native?ref=v0.14.8

# ---
# apiVersion: notification.toolkit.fluxcd.io/v1beta3
# kind: Alert
# metadata:
#   name: discord
#   namespace: coinvar
# spec:
#   summary: "Flux alert"
#   providerRef:
#     name: discord
#   eventSeverity: info
#   eventSources:
#     - kind: GitRepository
#       name: '*'
#     - kind: Kustomization
#       name: '*'
#     - kind: HelmRelease
#       name: '*'
#   # exclusionList:
#   #   - "^Reconciliation finished"