apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-to-discord
  namespace: homeautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-to-discord
  template:
    metadata:
      labels:
        app: mqtt-to-discord
    spec:
      
      # specificonly only workloads
      tolerations:
        - key: "la1r.workload/specificonly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "la1r.workload/specificonly"
                operator: "In"
                values:
                - "true"

      containers:
      - name: mqtt-to-discord
        image: python:3.9-slim
        command: ["sh", "-c", "pip install paho-mqtt requests && python /scripts/mqtt_to_discord.py"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        env:
        - name: FRIGATE_DISCORD_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: discord-webhooks
              key: FRIGATE_DISCORD_WEBHOOK
      volumes:
      - name: script-volume
        configMap:
          name: mqtt-to-discord-script
      restartPolicy: Always
