---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-config-claim
  namespace: homeautomation
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "homeassistant-config"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeautomation
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant-config-volume
          persistentVolumeClaim:
            claimName: homeassistant-config-claim
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant
        ports:
        - name: http
          containerPort: 8123
        env:
        - name: TZ
          value: "Europe//Amsterdam"
        - name: USER_ID
          value: "1000"
        - name: GROUP_ID
          value: "1000"
        volumeMounts:
          - name: homeassistant-config-volume
            mountPath: /config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeautomation
spec:
  ports:
  - name: http
    targetPort: 8123
    port: 80
  selector:
    app: homeassistant
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homeassistantingress
  namespace: homeautomation
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: homeassistant.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: homeassistant
          servicePort: 80
  - host: homeassistant.thuis
    http:
      paths:
      - path: /
        backend:
          serviceName: homeassistant
          servicePort: 80