---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400 #One day
      - name: Install required packages 
        apt: name={{item}} state=installed
        with_items:
            - apt-transport-https
            - ca-certificates
            - software-properties-common
        become: True
      - name: Add an Apt signing key, uses whichever key is at the URL
        apt_key:
          url: https://yum.dockerproject.org/gpg
          state: present
        become: True
      - name: Add key to repo
        apt_repository:
            repo: deb https://apt.dockerproject.org/repo/ raspbian-stretch main
            state: present
        become: True
      - name: Install docker 
        apt:
          name: docker-engine
          state: present
        become: True
      
      # - name: Download Docker install script
      #   get_url:
      #     url: https://get.docker.com
      #     dest: ~/install_docker.sh

      # - name: Install Docker
      #   command: bash ./install_docker.sh
      #   become: True
        # args:
        #   creates: /usr/bin/docker

      # - name: Install docker-py
      #   pip:
      #     name: docker-py
      #   become: True

      - name: Add {{ target_user }} to docker group
        user:
          name: "{{ target_user }}"
          groups: docker
          append: yes
        become: True
      - name: Start service docker, if not started
        service:
          name: docker
          state: started
        become: True

# TODO: remove hardcoded raspbian-stretch with $(lsb_release -cs) somehow