---
- name: restart ssh on non-centos
  become: yes
  service:
    name: ssh
    state: restarted
    enabled: yes
  when: ansible_facts['distribution'] != "CentOS"
  listen: restart ssh
  async: 45
  poll: 0

- name: restart ssh on centos
  become: yes
  service:
    name: sshd
    state: restarted
    enabled: yes
  when: ansible_facts['distribution'] == "CentOS"
  listen: restart ssh
  async: 45
  poll: 0