---

# - include_tasks: install-centos.yml
#   tags:
#     - kubernetes_server
#   when: ansible_lsb.id == "CentOS"
# - include_tasks: install-ubuntu.yml
#   tags:
#     - kubernetes_server
#   when: ansible_lsb.id == "Ubuntu"
- include_tasks: install-raspbian.yml
  tags:
    - kubernetes_server
  when: ansible_lsb.id == "Raspbian" or  ( ansible_lsb.id == "Ubuntu" and ansible_architecture =="aarch64")
- include_tasks: install-common.yml
  tags:
    - kubernetes_server
  

# - include_tasks: install-storage-prereq.yml
#   tags:
#     - storage_kubernetes
#   when: ansible_lsb.id != "Raspbian"
    
# - include_tasks: init-kubernetes.yml
#   tags:
#     - init_kubernetes
# - include_tasks: fetch-kubeconfig.yml
#   tags:
#     - fetch_kubernetes
# - include_tasks: join-kubernetes.yml
#   tags:
#     - join_kubernetes
# - include_tasks: reset-kubernetes.yml
#   tags:
#     - reset_kubernetes