---
# source: https://github.com/mateobur/prometheus-monitoring-guide/tree/master/alertmanager-example
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 3s
      group_interval: 10s
      repeat_interval: 7d
      receiver: discord_webhook

    receivers:
      - name: discord_webhook
        webhook_configs:
        - url: "http://monitoring-discord-webhook:9094"
          send_resolved: true
      # - name: http_webhook
      #   webhook_configs:
      #   - url: "http://requestbin.net/r/1kbudtc1"
      #     send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: monitoring-alertmanager
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: monitoring-alertmanager
    spec:
      containers:
      - name: alertmanager
        ports:
        - containerPort: 9093
        image: prom/alertmanager
        resources:
          requests:
            cpu: 10m
            memory: 56Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        # - name: alertmanager
        #   mountPath: /alertmanager
        - name: alertmanager-config
          mountPath: /etc/alertmanager/alertmanager.yml
          subPath: alertmanager.yml
        - mountPath: /alertmanager
          name: alertmanager-volume
      volumes:
      # - name: alertmanager
      #   persistentVolumeClaim:
      #     claimName: alertmanager-claim
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
          items:
          - key: alertmanager.yml
            path: alertmanager.yml
          defaultMode: 0744
      - name: alertmanager-volume
        persistentVolumeClaim:
          claimName: alertmanager-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
  name: monitoring-alertmanager-service
  namespace: monitoring
spec:
  ports:
  - name: alsohttp
    port: 9093
    targetPort: 9093
  - name: http
    port: 80
    targetPort: 9093
  selector:
    k8s-app: monitoring-alertmanager

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanageringress
  namespace: monitoring
spec:
  rules:
  - host: alerts.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-alertmanager-service
            port:
              number: 80


---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alert-manager-bas
  namespace: monitoring
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: alert-manager-bas-tls
  commonName: alerts.bas
  dnsNames:
  - alerts.bas
  - www.alerts.bas
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alert-manager-tls
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`alerts.bas`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: monitoring-alertmanager-service
      port: 80
  tls:
    secretName: alert-manager-bas-tls