---
# source: https://github.com/mateobur/prometheus-monitoring-guide/tree/master/alertmanager-example
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: discord_webhook

    receivers:
      - name: discord_webhook
        webhook_configs:
        - url: "http://monitoring-discord-webhook:9094"
          send_resolved: true
      # - name: http_webhook
      #   webhook_configs:
      #   - url: "http://requestbin.net/r/1kbudtc1"
      #     send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: monitoring-alertmanager
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: monitoring-alertmanager
    spec:
      containers:
      - name: alertmanager
        ports:
        - containerPort: 9093
        image: prom/alertmanager
        volumeMounts:
        # - name: alertmanager
        #   mountPath: /alertmanager
        - name: alertmanager-config
          mountPath: /etc/alertmanager/alertmanager.yml
          subPath: alertmanager.yml
      volumes:
      # - name: alertmanager
      #   persistentVolumeClaim:
      #     claimName: alertmanager-claim
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
          items:
          - key: alertmanager.yml
            path: alertmanager.yml
          defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
  name: monitoring-alertmanager-service
  namespace: monitoring
spec:
  ports:
  - name: alsohttp
    port: 9093
    targetPort: 9093
  - name: http
    port: 80
    targetPort: 9093
  selector:
    k8s-app: monitoring-alertmanager

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-alertmanager-ingress
  namespace: monitoring
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: alerts.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-alertmanager-service
          servicePort: 80