---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jackett-config-pv
  labels:
    contenttype: "jackett-config-data"
spec:
  capacity:
    storage: 1Gi
  storageClassName: jackett-config-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/jackett-config"