---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-claim
spec:
  storageClassName: jackett-config-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi