apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - pv
  - middleware.yml
  - auth-middleware.yml
  - openvscode-server.yml
  - container-build.yml
configMapGenerator:
- name: openvscode-server-init
  files:
  - init.sh
- name: openvscode-server-dockerfile
  files:
  - Dockerfile

generatorOptions:
  disableNameSuffixHash: true
