---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: exporter-openvpn-pv
  labels:
    contenttype: "exporter-openvpn"
spec:
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadOnlyMany
  local:
    path: /var/log/openvpn/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - linux-wayne