---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud-web-pv
  labels:
    contenttype: "nextcloud-web"
spec:
  capacity:
    storage: 5Gi
  storageClassName: nextcloud-web
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/ha/nextcloud/config" # path to directory
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud-data-pv
  labels:
    contenttype: "nextcloud-data"
spec:
  capacity:
    storage: 800Gi
  storageClassName: nextcloud-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd/ha/nextcloud/data" # path to directory
