---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ntfy-data-pv
  labels:
    contenttype: "ntfy-data"
spec:
  capacity:
    storage: 5Gi
  storageClassName: ntfy-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/ntfy/data"
