---
# - name: Configure all hosts
#   hosts: all
#   roles:
#     - { role: users, tags: ['users'] }
#     - { role: ssh, tags: ['ssh'] }
#     - { role: hostname, tags: ['hostname'] }
#     - { role: security, tags: ['security'] }


# - name: Configure remote nodes
#   hosts: remote
#   roles:
#     - { role: remote-backup, tags: ['remote-backup']}

- name: Configure cluster nodes
  hosts: cluster
  roles:
    - { role: samba, tags: ['samba']}



    # - { role: haproxy, tags: ['haproxy'], when: "'ha_proxy_settings' in hostvars[inventory_hostname]" }
#     - { role: kubernetes-install, tags: ['kubernetes'] }
#     - { role: kubernetes-join, tags: ['kubernetes'] }
