---
# - name: Configure all hosts
#   hosts: all
#   roles:
#     - { role: users, tags: ['users'] }
#     - { role: ssh, tags: ['ssh'] }
#     - { role: hostname, tags: ['hostname'] }
#     - { role: security, tags: ['security'] }

- name: Configure cluster nodes
  hosts: cluster
  roles:
    # - { role: samba, tags: ['samba']}
    # - { role: ubuntu-config, tags: ['ubuntu-config']}
    - { role: ufw, tags: ['ufw'] }
    - { role: fail2ban, tags: ['fail2ban'] }

- name: Install k3s (single-node) on stephanie
  hosts: stephanie
  roles:
    - { role: k3s, tags: ['k3s'] }

- name: Configure remote nodes
  hosts: remote
  roles:
    - { role: remote-wg, tags: ['remote-wg'], ignore_errors: yes }
    # FIXME: to update or remove# - { role: remote-backup, tags: ['remote-backup'], ignore_errors: yes }

    # - { role: haproxy, tags: ['haproxy'], when: "'ha_proxy_settings' in hostvars[inventory_hostname]" }
#     - { role: kubernetes-install, tags: ['kubernetes'] }
#     - { role: kubernetes-join, tags: ['kubernetes'] }
