---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
    - name: Check if packages are installed
      apt: name={{item}} state=present
      with_items:
          - nfs-common
    - name: "Edit /etc/idmapd.conf"
      lineinfile:
        dest: "/etc/idmapd.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Nobody-User',  line: 'Nobody-User = backup' }
        - { regexp: '^Nobody-Group', line: 'Nobody-Group = backup' }
    - name: "Edit /etc/fstab"
      lineinfile:
        dest: "/etc/fstab"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^10.8.0.18:/mnt/largehdd/backup',  line: '10.8.0.18:/mnt/largehdd/backup /mnt/remote/backup nfs rw 0 0' }