---
- name: Add Target User /  Add the user "{{ target_user_name }}"
  become: yes
  user:
    name: "{{ target_user_name }}"
    comment: "{{ target_user_comment }}"
    groups : "{{ 'sudo' if ansible_os_family == 'Debian' else '' }}" 
    append: yes
    state: present
    createhome: yes

