---
- name: Add Target User /  Set authorized key took from file for "{{ target_user_name }}"
  become: yes
  authorized_key:
    user: "{{ target_user_name }}"
    key: "{{ lookup('file', '../../credentials/ssh/id_rsa.pub') }}"
    state: present
  notify:
  - restart ssh
