- name: "Change Root Password / Include root credentials"
  include_vars:
    file: "{{credentials_dir}}/root/root-credentials.yaml"
- name: "Change Root Password / Change root password"
  become: yes
  shell: 'echo -e "{{root_password}}\n{{root_password}}" | passwd {{ target_user_name }}'
  args:
    executable: /bin/bash
  # notify:
  # - "restart ssh"
  