---
- name: Enable Sudo / Install sudo
  become: yes
  package:
    name: sudo
    state: present

- name: Enable Sudo / Add include for sudoers.d folder
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '#includedir /etc/sudoers.d'

- name: Enable Sudo / Create sudoers.d folder
  become: yes
  file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: Enable Sudo /  Add {{ target_user_name }} user to the sudoers
  become: yes
  copy:
      dest: "/etc/sudoers.d/{{ target_user_name }}"
      content: "{{ target_user_name }}  ALL=(ALL)  NOPASSWD: ALL"
