---
- include_tasks: check-target_user.yml
  # notify:
  #   - "ssh restart"
  tags: 
    - users

- include_tasks: enable-sudo.yml
  tags: 
    - users
  when: target_user_exists != true

- include_tasks: add-target_user.yml
  tags: 
    - users
  when: target_user_exists != true

- include_tasks: add_ssh_settings.yml
  tags: 
    - users
  when: target_user_exists != true



- include_tasks: swap-uid.yml
  tags: 
    - users
  when: target_user_exists != true
- include_tasks: change-root-password.yml
  tags: 
    - users
  when: target_user_exists != true
- include_tasks: remove-default_user.yml
  tags: 
    - users
  when: target_user_exists != true