apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enshrouded-pvc
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: enshrouded-savegame
  selector:
    matchLabels:
      contenttype: enshrouded-savegame