---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: nfs-211
  resources:
    requests:
      storage: 20Gi