---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ssd-na
  resources:
    requests:
      storage: 20Gi