---
# source: https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948
apiVersion: v1
kind: ServiceAccount
metadata:
  name: online-traefik-ingress-controller
  namespace: online
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-traefik-ingress-controller
  namespace: online
  labels:
    k8s-app: online-traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: online-traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: online-traefik-ingress-lb
        name: online-traefik-ingress-lb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - big-raver
      # volumes:
      # - name: ssl
      #   secret:
      #     secretName: traefik-cert
      #     defaultMode: 0744
      # - name: config
      #   configMap:
          # name: traefik-conf
          # defaultMode: 0744
          # items:
          #   - key: traefik.toml
          #     path: traefik.toml
      serviceAccountName: online-traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - name: online-traefik-ingress-lb
        image: traefik:v2.0
        # volumeMounts:
        # - mountPath: "/ssl"
        #   name: "ssl"
        # - mountPath: "/config"
        #   name: "config"
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
          hostPort: 8080
        # securityContext:
        #   capabilities:
        #     drop:
        #     - ALL
        #     add:
        #     - NET_BIND_SERVICE
        args:
          - --api.insecure
          - --accesslog
          - --metrics=true
          - --metrics.influxdb=true
          - --metrics.influxdb.address="monitoring-influxdb.monitoring:80"
          - --metrics.influxdb.database="online-traefik"
          - --entrypoints.web.Address=:80
          - --entrypoints.websecure.Address=:443
          # - --providers.kubernetesingress
---
kind: Service
apiVersion: v1
metadata:
  name: online-traefik-ingress-service
  namespace: online
spec:
  selector:
    k8s-app: online-traefik-ingress-lb
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: web
    - port: 443
      name: https
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080
      name: admin
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: online-traefik-web-ui
#   namespace: online
# spec:
#   rules:
#   - host: online-traefik.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: online-traefik-ingress-service
#           servicePort: admin