---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: online-traefik-config-pv
  labels:
    contenttype: "online-traefik-config"
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largessd/configs/online-traefik
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - linux-wayne