---
- name: Install haproxy /etc/sysctl.conf
  become: true
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^net.ipv4.ip_nonlocal_bind = ',  line: 'net.ipv4.ip_nonlocal_bind = 1' }

- name: Install haproxy / reload sysctl
  become: yes
  shell: |
    sysctl -p
    ip --brief add
  args:
    executable: /bin/bash

- name: Install haproxy / Install haproxy and keepalived
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - gcc
    - keepalived
    - haproxy
    # - openssl-devel
    # - openssl-devel
    # - kernel-headers
    # - kernel-devel
- name: Install haproxy / set haproxy.conf
  become: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
- name: Install haproxy / set keepalived.conf
  become: yes
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
- name: Install haproxy / Restart system services
  become: yes
  service: 
    name: "{{item}}"
    enabled: yes
    state: restarted
  with_items:
      - keepalived
      - haproxy
