---
apiVersion: v1
kind: ConfigMap
metadata:
  name: find-install
  namespace: event
data:
  find-install.sh : |-
    #!/bin/sh
    git clone https://github.com/schollz/find.git
    cd find
    go get ./...
    go build
    cp ./find ../
    cd ..
    
    # SVM setup
    apt-get install g++
    wget http://www.csie.ntu.edu.tw/~cjlin/cgi-bin/libsvm.cgi?+http://www.csie.ntu.edu.tw/~cjlin/libsvm+tar.gz -O libsvm.tar.gz
    tar -xvf libsvm.tar.gz -C ./
    cd libsvm-*
    make
    cp svm-scale /go/
    cp svm-predict /go/
    cp svm-train /go/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: find
  namespace: event
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: find
  template:
    metadata:
      labels:
        task: event
        k8s-app: find
    spec:
      initContainers:
      - name: find-build
        image: golang
        command: 
          - /bin/sh
          - -c
          - "/start/find-install.sh"
        volumeMounts:
        - name: find-install
          mountPath: /start
        - name: build-dir
          mountPath: /go
      containers:
      - name: find
        ports:
        - containerPort: 80
        image: golang
        command:
          - /bin/sh
          - -c
          - "export PATH=$PATH:/go ; cd /go/find/ ; ./find -mqtt raw:1883"
        volumeMounts:
          - name: build-dir
            mountPath: /go
          - name: find-install
            mountPath: /start
      volumes:
      - name: find-install
        configMap:
          name: find-install
          defaultMode: 0755
      - name: build-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: find
  name: find
  namespace: event
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: find