---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-web-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "web"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany  
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "data"
  resources:
    requests:
      storage: 800Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
      - name: mysqlini-volume
        configMap:
          name: mysqlini
          items:
          - key: mysql.ini
            path: mysql.ini
      - name: nextcloud-web
        persistentVolumeClaim:
          claimName: nextcloud-web-claim
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-claim
      containers:
      - name: nextcloud
        image: nextcloud
        ports:
        - containerPort: 80
        env:
        - name: NEXTCLOUD_TABLE_PREFIX
          value: ""
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: MYSQL_HOST
          value: "mariadb"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: password
        # volumeMounts:
        #   - mountPath: "/var/www/html"
        #     name: nextcloud-web
        #   - mountPath: "/var/www/html/data"
        #     name: nextcloud-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud-external
  namespace: nextcloud
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: nextcloud
  type: NodePort
