---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    contenttype: "cache"
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany 
  local:
    path: /mnt/largessd/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver