---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-claim
  namespace: monitoring
spec:
  storageClassName: alertmanager-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi