targets:
  - /mnt/hdd/media/bas/Pictures/Vroeger/2003
  - /mnt/hdd/media/bas/Pictures/Vroeger/2004
  - /mnt/hdd/media/bas/Pictures/Vroeger/2005
  - /mnt/hdd/media/bas/Pictures/Vroeger/2006
  - /mnt/hdd/media/bas/Pictures/Vroeger/2007
  - /mnt/hdd/media/bas/Pictures/Vroeger/2008
  - /mnt/hdd/media/bas/Pictures/Vroeger/2009
  - /mnt/hdd/media/bas/Pictures/Vroeger/2010
  - /mnt/hdd/media/bas/Pictures/Vroeger/2011
  - /mnt/hdd/media/bas/Pictures/Vroeger/2012
  - /mnt/hdd/media/bas/Pictures/Vroeger/2013
  - /mnt/hdd/media/bas/Pictures/Vroeger/2014
  - /mnt/hdd/media/bas/Pictures/Vroeger/2015
  - /mnt/hdd/media/bas/Pictures/Vroeger/2016
  - /mnt/hdd/media/bas/Pictures/Vroeger/2017
  - /mnt/hdd/media/bas/Pictures/Vroeger/2018
  - /mnt/hdd/media/bas/Pictures/Vroeger/2019
  - /mnt/hdd/media/bas/Pictures/Vroeger/2020
  - /mnt/hdd/media/bas/Pictures/Vroeger/2021
  - /mnt/hdd/media/bas/Pictures/Vroeger/2022
  - /mnt/hdd/media/bas/Pictures/Vroeger/2023
  - /mnt/hdd/media/bas/Pictures/Vroeger/2024
  - /mnt/hdd/media/bas/Pictures/Vroeger/2025
  - /mnt/hdd/media/bas/Pictures/Vroeger/2026