apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workflows
resources:
- pv
- workflow-glacier-cloud-backup.yml
- crons

configMapGenerator:
- name: glacier-backup-targets
  files:
  - targets=glacier-backup-targets.yml
  options:
    disableNameSuffixHash: true