apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: glacier-cloud-backup
  namespace: workflows
spec:
  entrypoint: glacier-cloud-backup
  podSpecPatch: |
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - jay-c
  arguments:
    parameters:
      - name: bucket
        value: "la1r-backup-glacier-backup-data"   # default bucket name
      - name: appname
      - name: storageclass
        value: "STANDARD_IA"
  volumes:
    - name: work # working dir
      persistentVolumeClaim:
        claimName: glacier-workingdir-claim
    - name: config
      configMap:
        name: glacier-backup-targets
  onExit: exit-handler
  templates:
    - name: glacier-cloud-backup
      dag:
        tasks:
          - name: encrypt-backup
            template: encrypt-backup
          - name: upload-backup
            depends: encrypt-backup
            template: upload-backup
            arguments:
              parameters:
                - name: bucket
                  value: "{{workflow.parameters.bucket}}"
                - name: appname
                  value: "{{workflow.parameters.appname}}"
                - name: storageclass
                  value: "{{workflow.parameters.storageclass}}"
      

    - name: encrypt-backup
      container:
        image: debian:bullseye-slim # can be any image with bash
        command: [sh, -c]
        args:
          - |
            apt update && apt install -y gnupg

            grep '^  - /' /mnt/config/targets | sed 's/^  - //' | while read -r localpath; do
              echo "=== Encrypting $localpath ==="
              mkdir -p "/mnt/work${localpath}"
              find "$localpath" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}' > "/mnt/work${localpath}/backup.sha256"
              tar -czf /tmp/backup.tar.gz "$localpath"
              gpg --output "/mnt/work${localpath}/backup.gpg" --encrypt --recipient-file /mnt/gpg/automation-gpg-public.asc /tmp/backup.tar.gz
              rm -f /tmp/backup.tar.gz
            done
        volumeMounts:
          - name: work
            mountPath: /mnt/work
          - name: hdd-ro-glacier
            mountPath: /mnt/hdd
            readOnly: true
          - name: gpg-automated-keys
            mountPath: /mnt/gpg/
          - name: config
            mountPath: /mnt/config
            readOnly: true
      volumes:
      - name: hdd-ro-glacier
        persistentVolumeClaim:
          claimName: hdd-ro-glacier-claim
          readOnly: true
      # GPG public key
      - name: gpg-automated-keys
        secret:
          secretName: gpg-automated-keys

    - name: upload-backup
      inputs:
        parameters:
          - name: bucket
          - name: appname
          - name: storageclass
      container:
        image: amazon/aws-cli:latest
        command: [sh, -c]
        args:
          - |
            grep '^  - /' /mnt/config/targets | sed 's/^  - //' | while read -r target; do
              TARGET_ID=$(echo "$target" | sed 's|/mnt/hdd/||' | sed 's|/|_|g')
              BUCKET_PATH="{{inputs.parameters.appname}}/${TARGET_ID}.gpg"
              echo "Uploading /mnt/work${target}/backup.gpg to bucket: {{inputs.parameters.bucket}} at: ${BUCKET_PATH}"
              NEW_SHA256=$(cat "/mnt/work${target}/backup.sha256" | tr -d '[:space:]')

              # Try to get existing object's sha256 tag
              # S3_SHA256=$(aws s3api get-object-tagging \
              #   --bucket "{{inputs.parameters.bucket}}" \
              #   --key "${BUCKET_PATH}" \
              #   --query "TagSet[?Key=='sha256'].Value | [0]" \
              #   --output text 2>/dev/null | tr -d '[:space:]')

              # echo "Local sha256: $NEW_SHA256, S3 sha256: $S3_SHA256"

              # if [ "$NEW_SHA256" != "$S3_SHA256" ]; then
              #     echo "SHA256 changed or object does not exist. Uploading new version..."
              #      aws s3api put-object \
              #       --bucket "{{inputs.parameters.bucket}}" \
              #       --key "${BUCKET_PATH}" \
              #       --body "/mnt/work${target}/backup.gpg" \
              #       --storage-class {{inputs.parameters.storageclass}} \
              #       --tagging "sha256=$NEW_SHA256" \
              #       --metadata sha256="$NEW_SHA256"
              # else
              #     echo "SHA256 matches existing metadata. Skipping upload."
              # fi
            done
        volumeMounts:
          - name: work
            mountPath: /mnt/work
          - name: config
            mountPath: /mnt/config
            readOnly: true
          - name: aws-credentials-volume
            mountPath: /root/.aws/credentials
            subPath: credentials
            readOnly: true
          - name: aws-config-volume
            mountPath: /root/.aws/config
            subPath: config
            readOnly: true
      volumes:
      # AWS credentials
      - name: aws-credentials-volume
        secret:
          secretName: aws-config-backup-uploader
          items:
            - key: credentials
              path: credentials
      - name: aws-config-volume
        secret:
          secretName: aws-config-backup-uploader
          items:
            - key: config
              path: config

    - name: clean-workingdir
      container:
        image: debian:bullseye-slim # can be any image with bash
        command: [sh, -c]
        args:
          - |
            echo "Cleaning workingdir"
            grep '^  - /' /mnt/config/targets | sed 's/^  - //' | while read -r target; do
              rm -rf "/mnt/work${target}"
            done
        volumeMounts:
          - name: work
            mountPath: /mnt/work
          - name: config
            mountPath: /mnt/config
            readOnly: true
    
    - name: exit-handler
      dag:
        tasks:
          # - name: notify-success
          #   template: notify
          #   when: "{{workflow.status}} == Succeeded"
          #   arguments:
          #     parameters:
          #       - name: status
          #         value: "Succeeded"
          - name: notify-failure
            template: notify
            when: "{{workflow.status}} != Succeeded"
            arguments:
              parameters:
                - name: status
                  value: "Failed"
          - name: cleanup
            depends: "notify-success.Succeeded || notify-success.Failed || notify-success.Skipped || notify-failure.Succeeded || notify-failure.Failed || notify-failure.Skipped"
            template: clean-workingdir

    - name: notify
      inputs:
        parameters:
          - name: status
      container:
        image: curlimages/curl:8.7.1
        command: [sh, -c]
        args:
          - |
            set -euo pipefail
            URL="http://ntfy.monitoring.svc.cluster.local/backup"
            MSG="{{workflow.parameters.appname}} backup {{inputs.parameters.status}} for workflow {{workflow.name}} in ns {{workflow.namespace}}. Bucket: {{workflow.parameters.bucket}}"
            echo "Sending ntfy notification to $URL"
            curl -fsS -X POST \
              -H "Title: {{workflow.parameters.appname}} backup {{inputs.parameters.status}}" \
              --data "$MSG" \
              "$URL"