apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:main
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: upload-volume
          mountPath: /usr/src/app/upload2
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        envFrom:
        - secretRef:
            name: db-secrets
        env:
        - name: DB_PASSWORD
          value: mysecretpassword
          # valueFrom:
          #   secretKeyRef:
          #     name: db-secrets
          #     key: POSTGRES_PASSWORD
        - name: DB_USERNAME
          value: mydbuser
          # valueFrom:
          #   secretKeyRef:
          #     name: db-secrets
          #     key: POSTGRES_USER
        - name: DB_DATABASE_NAME
          value: immich
        - name: REDIS_PORT
          value: "6379"
        - name: UPLOAD_LOCATION
          value: "/usr/src/app/upload"
      volumes:
      - name: upload-volume
        persistentVolumeClaim:
          claimName: immich-server-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
