---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye
  namespace: homeautomation
  labels:
    app: motioneye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motioneye
  template:
    metadata:
      labels:
        app: motioneye
    spec:
      volumes:
        - name: motioneye-data-volume
          persistentVolumeClaim:
            claimName: motioneye-data-claim
        - name: motioneye-config-volume
          persistentVolumeClaim:
            claimName: motioneye-config-claim
      containers:
      - name: motioneye
        image: ccrisan/motioneye:master-amd64
        resources:
          requests:
            cpu: 400m
            memory: 512Mi
          limits:
            cpu: 600m
            memory: 1Gi
        ports:
        - name: http
          containerPort: 8765
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: motioneye-config-volume
            mountPath: /etc/motioneye 
          - name: motioneye-data-volume
            mountPath: /var/lib/motioneye
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: motioneye
#   name: motioneye
#   namespace: homeautomation
# spec:
#   ports:
#   - name: http
#     targetPort: 8765
#     port: 80
#   selector:
#     app: motioneye
#   type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: motioneye
  name: motioneye
  namespace: homeautomation
spec:
  ports:
  - name: http
    targetPort: 8765
    port: 80
  selector:
    app: motioneye
  loadBalancerIP: 192.168.6.75
  type: LoadBalancer

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: motioneyeingress
#   namespace: homeautomation
# spec:
#   rules:
#   - host: cam.bas
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: motioneye
#             port:
#               number: 80

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: motioneye-bas
#   namespace: homeautomation
# spec:
#   issuerRef:
#     name: la1r
#     kind: ClusterIssuer
#   secretName: motioneye-bas-tls
#   commonName: cam.bas
#   dnsNames:
#   - cam.bas
#   - www.cam.bas
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: motioneye-tls
#   namespace: homeautomation
# spec:
#   entryPoints:
#     - websecure
#   routes:
#   - match: Host(`cam.bas`) && PathPrefix(`/`)
#     kind: Rule
#     services:
#     - name: motioneye
#       port: 80
#   tls:
#     secretName: motioneye-bas-tls