---
- name: Copy install script
  template: src=install.sh.j2 dest={{home_dir}}/noip_install.sh mode=0755

- name: Install noip
  command: sh ./noip_install.sh
  become: True

- name: Install noip init.d
  template: src=initd.j2 dest={{noip_initd}} mode=0700
  sudo: True

- name: Copy monit config
  template: src=noip2.monitrc.j2 dest=/etc/monit/conf.d/noip2.monitrc
  sudo: True
  notify:
    - reload monit
