---
all:
  children:
    cluster:
      hosts:
        linux-wayne:
        # stephanie:
        jay-c:
    # peripheral:
    #   hosts:
    #     ali-bel:
    #       ansible_host: 192.168.9.71
    #     kodi-e:
    #       ansible_host: 192.168.15.243
    remote:
      hosts:
        remote-cube:
          ansible_host: 10.8.0.4
          ansible_user: basraven
          ansible_ssh_common_args: '-o ProxyJump=basraven@192.168.5.1'