---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enshrouded
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enshrouded
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: enshrouded
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: la1r.workload/nonessential
      #           operator: In
      #           values:
      #           - "true"
      containers:
      - name: enshrouded
        image: sknnr/enshrouded-dedicated-server:latest
        # securityContext:
        #   runAsUser: 1000
        #   runAsGroup: 1000
        env:
        - name: SERVER_NAME
          value: "RAVER"
        - name: SERVER_SLOTS
          value: "16"
        - name: SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enshrouded-secret
              key: SERVER_PASSWORD
        - name: PORT
          value: "15637"
        ports:
        - containerPort: 15637
          protocol: UDP
          name: game
        - containerPort: 27015
          protocol: UDP
          name: steam-query
        resources:
          limits:
            cpu: "10"
            memory: "20Gi"
          requests:
            cpu: "8"
            memory: "15Gi"
        volumeMounts:
        - name: savegame
          mountPath: /home/steam/enshrouded/savegame
      volumes:
      - name: savegame
        persistentVolumeClaim:
          claimName: enshrouded-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: enshrouded-lb
  namespace: gaming
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.6.46
  externalTrafficPolicy: Local # To ensure that external traffic arriving at the LoadBalancer IP 192.168.6.46 stays on the same node where both the enshrouded server pod and traffic watcher are running.
  ports:
  - name: game
    port: 15637
    targetPort: 15637
    protocol: UDP
  - name: steam-query
    port: 27015
    targetPort: 27015
    protocol: UDP
  selector:
    app: enshrouded