---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: torrent
  labels:
    app: jellyfin
    sablier.enable: "true"
    sablier.group: jellyfin
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"
      runtimeClassName: nvidia
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        resources:
          limits:
            nvidia.com/gpu: 1
        #   requests:
        #     memory: "1024Mi"
        #     cpu: "300m"
        #   limits:
        #     memory: "3Gi"
        #     cpu: "2000m"
        ports:
        - name: http
          containerPort: 8096
        env:
        - name: TZ
          value: "Europe//Amsterdam"
        - name: JELLYFIN_PublishedServerUrl
          value: "http://192.168.6.2:8096/"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,video,utility"
        volumeMounts:
          - name: jellyfin-torrent-volume
            mountPath: /torrent
          - name: jellyfin-cache-volume
            mountPath: /cache
          - name: jellyfin-config-volume
            mountPath: /config
          - name: jellyfin-media-gezin-videos-volume
            mountPath: /gezin/Video
            readOnly: true
          # - name: jellyfin-transcode-volume
          #   mountPath: /transcode
      volumes:
        - name: jellyfin-torrent-volume
          persistentVolumeClaim:
            claimName: jellyfin-torrent-data-claim
        - name: jellyfin-cache-volume
          persistentVolumeClaim:
            claimName: jellyfin-cache-claim
        - name: jellyfin-config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config-claim
        - name: jellyfin-media-gezin-videos-volume
          persistentVolumeClaim:
            claimName: jellyfin-media-gezin-videos-claim
        # - name: jellyfin-transcode-volume
        #   persistentVolumeClaim:
        #     claimName: jellyfin-transcode-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: torrent
spec:
  ports:
  - name: jellyfin
    port: 8096
    targetPort: 8096
  selector:
    app: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-lb
  namespace: torrent
spec:
  ports:
  - name: jellyfin
    port: 8096
    targetPort: 8096
  selector:
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 192.168.6.61

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-bas
  namespace: torrent
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: jellyfin-bas-tls
  commonName: jellyfin.bas
  dnsNames:
  - jellyfin.bas
  - www.jellyfin.bas
  ipAddresses:
  - 192.168.6.2


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-https
  namespace: torrent
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "torrent-sablier-jellyfin@kubernetescrd"
spec:
  tls:
  - secretName: jellyfin-bas-tls
  rules:
  - host: jellyfin.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin
            port:
              number: 8096

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-jellyfin-ingress
  namespace: torrent
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "jellyfin"
    traefik.ingress.kubernetes.io/router.middlewares: "torrent-sablier-jellyfin@kubernetescrd"
spec:
  entryPoints:
    - jellyfin
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: jellyfin
          port: 8096
      middlewares:
      - name: sablier-jellyfin
        namespace: torrent