---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: torrent
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
      - name: torrent
        persistentVolumeClaim:
          claimName: torrent-claim
      containers:
      - name: plex
        image: linuxserver/plex:latest
        ports:
        - containerPort: 32400
        - containerPort: 32469
        - containerPort: 5353
        - containerPort: 1900
        volumeMounts:
          - name: torrent
            mountPath: "/data"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex
  namespace: torrent
spec:
  ports:
  - name: http
    port: 32400
  selector:
    app: plex
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plexingress
  namespace: torrent
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: plex.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400