---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: torrent-claim
  namespace: torrent
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "torrent"
  resources:
    requests:
      storage: 500Gi