apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeautomation
resources:
  - samba-traffic-listener.yml

configMapGenerator:
- name: samba-traffic-listener-script
  files:
  - samba-traffic-listener.go