apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-traffic-listener
  namespace: homeautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-traffic-listener
  template:
    metadata:
      labels:
        app: samba-traffic-listener
    spec:
      
      # Essential
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: la1r.workload/essential
                operator: In
                values:
                - "true"
      priorityClassName: essential

      containers:
      - name: samba-traffic-listener
        image: python:3.9-slim
        command: ["sh", "-c", "pip install requests watchdog kubernetes protobuf==3.20.* && python /scripts/samba-traffic-listener.py"]
        # command: ["sh", "-c", "pip install requests watchdog kubernetes protobuf==3.20.* && sleep 10000000"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        env:
        - name: RECHECK_INTERVAL
          value: "60" # in seconds
      volumes:
      - name: script-volume
        configMap:
          name: samba-traffic-listener-script
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: samba-traffic-listener
  name: samba-traffic-listener
  namespace: homeautomation
spec:
  ports:
  - name: netbiossamba
    port: 139
    targetPort: 139
  - name: directsamba
    port: 445
    targetPort: 445
  selector:
    app: samba-traffic-listener
  type: ClusterIP
