---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: torrent
  labels:
    app: jellyseerr
    sablier.enable: "true"
    sablier.group: jellyfin
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      priorityClassName: torrent-priority
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"

      volumes:
        - name: jellyseerr-config-volume
          persistentVolumeClaim:
            claimName: jellyseerr-config-claim
        # - name: jellyseerr-torrent-volume
        #   persistentVolumeClaim:
        #     claimName: jellyseerr-torrent-data-claim
      containers:
      - name: jellyseerr
        resources:
        image: ghcr.io/fallenbagel/jellyseerr
        ports:
        - name: http
          containerPort: 5055
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: port
          value: "5055" # default 5055
        volumeMounts:
          - name: jellyseerr-config-volume
            mountPath: /app/config
          # - name: jellyseerr-torrent-volume
          #   mountPath: /downloads
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyseerr
  name: jellyseerr
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 5055
    port: 80
  selector:
    app: jellyseerr
  type: ClusterIP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-bas
  namespace: torrent
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: jellyseerr-bas-tls
  commonName: jellyseerr.bas
  dnsNames:
  - jellyseerr.bas
  - www.jellyseerr.bas
  - basflix.bas
  - www.basflix.bas
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr-https
  namespace: torrent
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "torrent-sablier-jellyseerr@kubernetescrd"
spec:
  tls:
  - secretName: jellyseerr-bas-tls
  rules:
  - host: jellyseerr.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyseerr
            port:
              number: 80
  - host: basflix.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyseerr
            port:
              number: 80