---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sablier-jellyseerr
  namespace: torrent
spec:
  plugin:
    sablier:
      group: jellyseer
      # blocking:
      #   defaultTimeout: 10s
      dynamic:
        displayName: Jellyseerr
        refreshFrequency: 5s
        showDetails: "true"
        theme: shuffle
      sablierUrl: http://sablier:10000
      sessionDuration: 30m