---
apiVersion: v1
kind: Service
metadata:
  name: consul-dns-webui-loadbalancer-service
  namespace: dns
spec:
  loadBalancerIP: 192.168.6.91
  type: LoadBalancer
  ports:
    - name: webui
      # protocol: TCP
      targetPort: 8500
      port: 80
    - name: dns
      # protocol: TCP
      targetPort: 53
      port: 53
  selector:
    app: consul-dns

---
apiVersion: v1
kind: Service
metadata:
  name: consul-dns
  namespace: dns
  labels:
    name: consul-dns
spec:
  selector:
    app: consul-dns
  clusterIP: None
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-dns-dnsmasq
  namespace: dns
data:
  dnsmasq.conf: |-
    # Configuration file for dnsmasq.
    #
    # Format is one option per line, legal options are the same
    # as the long options legal on the command line. See
    # "/usr/sbin/dnsmasq --help" or "man 8 dnsmasq" for details.

    # Listen on this specific port instead of the standard DNS port
    # (53). Setting this to zero completely disables DNS function,
    # leaving only DHCP and/or TFTP.
    port=53


    # FIXME: Translations
    # server=/.bas/.service.bas/
    # server=/.bas/.service.bas/127.0.0.1#8600
    
    
    server=127.0.0.1#8600
       
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-dns
  namespace: dns
spec:
  serviceName: consul-dns
  selector:
    matchLabels:
      app: consul-dns
  replicas: 3
  template:
    metadata:
      labels:
        app: consul-dns
    spec:
      # affinity:
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #           - key: app
        #             operator: In
        #             values:
        #               - consul
        #       topologyKey: kubernetes.io/hostname
        # FIXME: doesnt work cross-node...
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution :
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: kubernetes.io/hostname
        #         operator: In
        #         values:
        #         - linux-wayne
      securityContext:
        fsGroup: 1000
      volumes:
      - name: consul-ingresses-storage-volume
        persistentVolumeClaim:
          claimName: consul-ingresses-storage
      - name: consul-dns-dnsmasq-volume
        configMap:
          name: consul-dns-dnsmasq
          items:
          - key: dnsmasq.conf
            path: dnsmasq.conf
          defaultMode: 0600
      containers:
        - name: dnsmasq
          volumeMounts:
          - name: consul-dns-dnsmasq-volume
            mountPath: /etc/dnsmasq.conf
            subPath: dnsmasq.conf
          image: alpine
          command: 
          - "sh"
          args: 
          - "-c"
          - |
              apk --no-cache add dnsmasq
              dnsmasq -k
          ports:
            - containerPort: 53
              name: dns
        - name: consul-dns
          volumeMounts:
          - name: consul-ingresses-storage-volume
            mountPath: /ingresses
          image: "consul"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bootstrap-expect=2"
            - "-retry-join=consul-dns-0.consul-dns.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-dns-1.consul-dns.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-dns-2.consul-dns.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
            - "-datacenter=rave"
            - "-domain=bas"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
            - "-config-dir=/ingresses"
            # - "-data-dir=/consul/data"
          # volumeMounts:
          #   - name: data
          #     mountPath: /consul/data
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
