# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: consul-dns
#   namespace: dns
#   labels:
#     app: consul-dns
# spec:
#   serviceName: consul-dns
#   replicas: 3
#   selector:
#     matchLabels:
#       app: consul-dns
#   template:
#     metadata:
#       labels:
#         app: consul-dns
#     spec:
#       containers:
#       - name: consul-dns
#         image: consul
#         env:
#         - name: POD_IP
#           valueFrom:
#             fieldRef:
#               fieldPath: status.podIP
#         - name: NAMESPACE
#           valueFrom:
#             fieldRef:
#               fieldPath: metadata.namespace
#         ports:
#         - name: webui
#           containerPort: 8500
#         - containerPort: 8301
#           name: serflan
#         - containerPort: 8302
#           name: serfwan
#         - containerPort: 8600
#           name: consuldns
#         - containerPort: 8300
#           name: server
#         # env:
#         #   - name: "CONSUL_BIND_INTERFACE"
#         #     value: "eth0"
#         args:
#           - agent
#           - -server
#           - -bootstrap-expect=3
#           - "-advertise=$(POD_IP)"
#           - "-retry-join=consul-dns-0.consul.$(NAMESPACE).svc.cluster.local"
#           - "-retry-join=consul-dns-1.consul.$(NAMESPACE).svc.cluster.local"
#           - "-retry-join=consul-dns-2.consul.$(NAMESPACE).svc.cluster.local"
#           - -ui
#           - -client=0.0.0.0
#           - -recursor=1.1.1.1
#           - "-domain=cluster.local"
#           - "-disable-host-node-id"
#           - -datacenter=rave
#           # - "-advertise=$(POD_IP)"
#           # - -dns-port=8600

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: consul-dns
#   name: consul-dns
#   namespace: dns
# spec:
#   # Headless service
#   clusterIP: None
#   ports:
#   - name: serflan-tcp
#     protocol: "TCP"
#     port: 8301
#     targetPort: 8301
#   - name: serflan-udp
#     protocol: "UDP"
#     port: 8301
#     targetPort: 8301
#   - name: serfwan-tcp
#     protocol: "TCP"
#     port: 8302
#     targetPort: 8302
#   - name: serfwan-udp
#     protocol: "UDP"
#     port: 8302
#     targetPort: 8302
#   - name: server
#     port: 8300
#     targetPort: 8300
#   - name: consuldns
#     port: 8600
#     targetPort: 8600
#   selector:
#     app: consul-dns
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: consul-dns
#   namespace: dns
# spec:
#   rules:
#   - host: consul-dns.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: consul-dns
#           servicePort: 80 

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: consul-dns-dns-loadbalancer-service
#   namespace: dns
# spec:
#   loadBalancerIP: 192.168.6.90
#   type: LoadBalancer
#   ports:
#     - name: dns
#       protocol: UDP
#       port: 53
#       targetPort: 8600
#   selector:
#     app: consul-dns

---
apiVersion: v1
kind: Service
metadata:
  name: consul-dns-webui-loadbalancer-service
  namespace: dns
spec:
  loadBalancerIP: 192.168.6.91
  type: LoadBalancer
  ports:
    - name: webui
      protocol: TCP
      targetPort: 8500
      port: 80
  selector:
    app: consul

---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: dns
  labels:
    name: consul
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: consul


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: dns
spec:
  serviceName: consul
  selector:
    matchLabels:
      app: consul
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      affinity:
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #           - key: app
        #             operator: In
        #             values:
        #               - consul
        #       topologyKey: kubernetes.io/hostname
        # FIXME: doesnt work cross-node...
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution :
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: kubernetes.io/hostname
        #         operator: In
        #         values:
        #         - linux-wayne
      securityContext:
        fsGroup: 1000
      containers:
        - name: consul
          image: "consul"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bootstrap-expect=2"
            - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
            - "-datacenter=rave"
            - "-domain=cluster.local"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
            # - "-data-dir=/consul/data"
          # volumeMounts:
          #   - name: data
          #     mountPath: /consul/data
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
          ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"