---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-k8s
  namespace: dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-reader-services
  namespace: dns
rules:
- apiGroups: ["", "endpoints", "extensions", "apps"]
  resources: ["endpoints", "events", "namespaces", "nodes", "pods", "customresourcedefinitions",  "apiservices", "daemonsets", "deployments", "statefulsets", "events", "ingresses", "ingresses", "services"]
  verbs: ["get", "watch", "list"]
# - apiGroups: [""]
#   resources: ["services"]
#   verbs: ["get","watch","list"]
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get","watch","list"]
# - apiGroups: ["extensions"]
#   resources: ["ingresses"]
#   verbs: ["get","watch","list"]
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["get", "list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: consul-k8s-all-reader-services-role-binding
subjects:
- kind: ServiceAccount
  name: consul-k8s
  namespace: dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: consul-k8s
  namespace: dns
spec:
  selector:
    matchLabels:
      app: consul-k8s
  template:
    metadata:
      labels:
        app: consul-k8s
    spec:
      serviceAccountName: consul-k8s
      containers:
        - name: consul-k8s
          image: "hashicorp/consul-k8s"
          command:
            - consul-k8s
          args:
            - sync-catalog
            - -to-consul=true
            - -to-k8s=false
            - -http-addr=http://consul-dns:8500
            - -allow-k8s-namespace=*
            - -deny-k8s-namespace=kube-system
            # - -allow-k8s-namespace=default
            # - -allow-k8s-namespace=kube-system