---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zeppelin-claim
  namespace: analytics
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "zeppelin"
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin
  namespace: analytics
  labels:
    app: zeppelin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        task: zeppelin
        k8s-app: zeppelin
        app: zeppelin
    spec:
      containers:
      - name: zeppelin
        ports:
        - containerPort: 8080 
        image: apache/zeppelin:0.8.2
        env:
        - name: ZEPPELIN_NOTEBOOK_DIR
          value: "/notebook"
        volumeMounts:
          - name: zeppelin
            mountPath: /notebook
      volumes:
        - name: zeppelin
          persistentVolumeClaim:
            claimName: zeppelin-claim
---
apiVersion: v1
kind: Service
metadata:
  name: zeppelin
  namespace: analytics
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: zeppelin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zeppelin
  namespace: analytics
spec:
  rules:
  - host: zeppelin.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: zeppelin
          servicePort: 80