---

# CentOS
- name: Install Docker / Add docker-ce to package repo for CentOS and install --nobest version (older containerd.io versioned)
  become: yes
  shell: |
    dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
    dnf install -y --nobest docker-ce
  args:
    executable: /bin/bash
  when: ansible_facts['distribution'] == "CentOS"
  async: 300
  poll: 5

- name: Install Docker / Disable firewalld for CentOS, we are using ufw
  become: yes
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    force: yes
  when: ansible_facts['distribution'] == "CentOS"

# Non CentOS
- name: Install Docker / Install docker-ce for non CentOS
  become: yes
  shell:  'curl -sSL get.docker.com | CHANNEL=test sh' # We use test build, following channels available: nightly, test, stable
  args:
    executable: /bin/bash
  when: ansible_facts['distribution'] != "CentOS"
  async: 300
  poll: 5


# Common
- name: Add {{ target_user_name }} to docker group
  become: yes
  user:
    name: "{{ target_user_name }}"
    groups:
      - docker 
    append: yes

- name: Start service docker, if not started
  become: yes
  service:
    name: docker
    enabled: yes
    state: started

