---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: heimdall
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: linuxserver/heimdall
        volumeMounts:
          - name: heimdall
            mountPath: /config
      volumes:
        - name: heimdall
          persistentVolumeClaim:
            claimName: heimdall-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    # kubernetes.io/cluster-service: 'true'
    # kubernetes.io/name: heimdall
  name: heimdall
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 80
  # type: NodePort
  selector:
    k8s-app: heimdall

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "heimdall"
  namespace: monitoring

spec:
  rules:
    - host: heimdall.bas
      http:
        paths:
          - path: /
            backend:
              serviceName: heimdall
              servicePort: 80

# ---
# kind: Ingress
# apiVersion: extensions/v1beta1
# metadata:
#   name: heimdall
#   namespace: monitoring
# spec:
#   rules:
#     - host: heimdal.bas
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: heimdall
#               servicePort: 80
          

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: heimdall
#   namespace: monitoring
# spec:
#   rules:
#   - host: heimdall.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: heimdall
#           servicePort: 80
#   - host: home.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: heimdall
#           servicePort: 80
#   - host: home.thuis
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: heimdall
#           servicePort: 80