---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall-claim
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "heimdall"
  resources:
    requests:
      storage: 2Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heimdall
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heimdall
    spec:
      containers:
      - name: heimdall
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: linuxserver/heimdall
        volumeMounts:
          - name: heimdall
            mountPath: /config
      volumes:
        - name: heimdall
          persistentVolumeClaim:
            claimName: heimdall-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: heimdall
  name: heimdall
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: heimdall
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heimdall
  namespace: monitoring
spec:
  rules:
  - host: heimdall.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: heimdall
          servicePort: 80
  - host: home.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: heimdall
          servicePort: 80
  - host: portal.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: heimdall
          servicePort: 80