---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: default
  labels:
    app: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
      - name: status
        image: nginxdemos/hello
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: status
  name: status
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: status
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: status-default
  namespace: default
  labels:
    expose: online
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`dev.la1r.com`)
    kind: Rule
    services:
    - name: status
      port: 80