---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-init
  namespace: event
data:
  telegraf-init.iql: CREATE DATABASE telegraf; 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-event-data-claim
  namespace: event
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "influx-event-data"
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-influxdb
  namespace: event
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: event-influxdb
  template:
    metadata:
      labels:
        task: event
        k8s-app: event-influxdb
    spec:
      containers:
      - name: influxdb
        ports:
        - containerPort: 8086
        image: influxdb
        volumeMounts:
        - name: influx-event-data-volume
          mountPath: /var/lib/influxdb
        - name: influxdb-init
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: INFLUXDB_DB
            value: k8s
          - name: INFLUXDB_USER
            value: bas
          - name: INFLUXDB_USER_PASSWORD
            value: Example1
      volumes:
      - name: influxdb-init
        configMap:
          name: influxdb-init
          defaultMode: 0755
      - name: influx-event-data-volume
        persistentVolumeClaim:
          claimName: influx-event-data-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: event-influxdb
  name: event-influxdb
  namespace: event
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    k8s-app: event-influxdb
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: event-influxdb
#   namespace: event
# spec:
#   rules:
#   - host: event-influxdb.bas
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: event-influxdb
#           servicePort: 80