---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-mariadb-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nextcloud-mariadb
  selector:
    matchLabels:
      contenttype: "nextcloud-mariadb"
  resources:
    requests:
      storage: 30Gi