---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud-mariadb-pv
  labels:
    contenttype: "nextcloud-mariadb"
spec:
  capacity:
    storage: 30Gi
  storageClassName: nextcloud-mariadb
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/ha/nextcloud/database" # path to directory