---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: openvscode-server-data-pv
  labels:
    contenttype: "openvscode-server-data"
spec:
  capacity:
    storage: 10Gi
  storageClassName: openvscode-server-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/ha/openvscode-server/data"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: openvscode-server-home-pv
  labels:
    contenttype: "openvscode-server-home"
spec:
  capacity:
    storage: 10Gi
  storageClassName: openvscode-server-home
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/ha/openvscode-server/home"