---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvscode-server-data-claim
spec:
  storageClassName: openvscode-server-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvscode-server-home-claim
spec:
  storageClassName: openvscode-server-home
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
