---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-na
  resources:
    requests:
      storage: 10Gi