---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-112
  resources:
    requests:
      storage: 20Gi