---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-traefik-config-claim
  namespace: online
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi