---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bazarr-config-data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-torrent-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bazarr-torrent-data
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-torrent-ssd-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bazarr-torrent-ssd-data
  resources:
    requests:
      storage: 200Gi
