---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sablier-monica
  namespace: crm
spec:
  plugin:
    sablier:
      group: monica
      # blocking:
      #   defaultTimeout: 10s
      dynamic:
        displayName: Monica
        refreshFrequency: 5s
        showDetails: "true"
        theme: shuffle
      sablierUrl: http://sablier:10000 # Sends: /api/strategies/dynamic?display_name=Immich&group=jellyfin&refresh_frequency=5s&session_duration=180m&show_details=true&theme=shuffle
      sessionDuration: 30m