---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-push-gateway-data-claim
  namespace: monitoring
spec:
  storageClassName: prometheus-push-gateway-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
