---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: consul-exporter
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: consul-exporter
    spec:
      containers:
      - name: consul-exporter
        resources:
        image: prom/consul-exporter
        args:
          - "--consul.server=consul.dns:8500"
        ports:
        - containerPort: 9107
---
apiVersion: v1
kind: Service
metadata:
  name: consul-exporter
  namespace: monitoring
spec:
  ports:
  - port: 9107
    targetPort: 9107
  selector:
    k8s-app: consul-exporter
