---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-config-pv
  labels:
    contenttype: "sonarr-config"
spec:
  capacity:
    storage: 1Gi
  storageClassName: sonarr-config-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/sonarr-config"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-torrent-data-pv
  labels:
    contenttype: "sonarr-torrent-data"
spec:
  capacity:
    storage: 10Gi
  storageClassName: sonarr-torrent-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd/torrent"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-torrent-ssd-data-pv
  labels:
    contenttype: "sonarr-torrent-ssd-data"
spec:
  capacity:
    storage: 200Gi
  storageClassName: sonarr-torrent-ssd-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/torrent-ssd"
