---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sonarr-config-data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-torrent-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sonarr-torrent-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-torrent-ssd-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sonarr-torrent-ssd-data
  resources:
    requests:
      storage: 200Gi
      