---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data-claim
  namespace: analytics
spec:
  storageClassName: nfs-212
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
