---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shieldsk8s
  namespace: online
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-reader-services
  namespace: online
rules:
- apiGroups: ["", "endpoints", "extensions", "apps"]
  resources: ["endpoints", "events", "namespaces", "nodes", "pods", "customresourcedefinitions",  "apiservices", "daemonsets", "deployments", "statefulsets", "events", "ingresses", "ingresses", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["traefik.containo.us"]
  resources: ["middlewares","ingressroutes","traefikservices","ingressroutetcps","ingressrouteudps","tlsoptions","tlsstores","serverstransports"]
  verbs: ["get", "list", "watch"]

# - apiGroups: [""]
#   resources: ["services"]
#   verbs: ["get","watch","list"]
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get","watch","list"]
# - apiGroups: ["extensions"]
#   resources: ["ingresses"]
#   verbs: ["get","watch","list"]
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["get", "list","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shieldsk8s-all-reader-services-role-binding
subjects:
- kind: ServiceAccount
  name: shieldsk8s
  namespace: online
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-reader-services
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shieldsk8s-admin-services-role-binding
subjects:
- kind: ServiceAccount
  name: shieldsk8s
  namespace: online
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldsk8s
  namespace: online
spec:
  selector:
    matchLabels:
      app: shieldsk8s
  template:
    metadata:
      labels:
        app: shieldsk8s
    spec:
      serviceAccountName: shieldsk8s
      restartPolicy: Always
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.6.90
      containers:
        - name: shieldsk8s
          ports:
          - containerPort: 44444
          image: "python"
          command:
            - sh
          args:
            - "-c"
            - |
              GIT_SSH_COMMAND='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' \
              git clone -q https://github.com/basraven/shieldsk8s.git ;
              cd shieldsk8s ; git checkout main ; cd ..
              pip3 install ./shieldsk8s ;
              export K8S_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              export K8S_CA_AUTH="$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 -w 0 )"
              mkdir -p ~/.kube

              echo "apiVersion: v1
              kind: Config
              users:
              - name: svcs-acct-dply
                user:
                  token: $K8S_TOKEN
              clusters:
              - cluster:
                  certificate-authority-data: $K8S_CA_AUTH
                  token: $K8S_TOKEN
                  server: https://192.168.5.100:443
                name: self-hosted-cluster
              contexts:
              - context:
                  cluster: self-hosted-cluster
                  user: svcs-acct-dply
                name: svcs-acct-context
              current-context: svcs-acct-context
              " > ~/.kube/config
              
              shieldsk8s expose
              
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shieldsk8s
  name: shieldsk8s
  namespace: online
spec:
  ports:
  - name: http
    targetPort: 44444
    port: 80
  selector:
    app: shieldsk8s
  type: ClusterIP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shieldsk8s-non-tls
  namespace: online
  labels:
    expose: "online"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`shieldsk8s.la1r.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: shieldsk8s
      port: 80
    middlewares:
    - name: online-ratelimit
      namespace: online
    - name: http-redirect-to-https
      namespace: online
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shieldsk8s-tls
  namespace: online
  labels:
    expose: "online"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`shieldsk8s.la1r.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: shieldsk8s
      port: 80
    middlewares:
    - name: online-ratelimit
      namespace: online
  tls:
    certResolver: default

