---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rutorrent-torrent-claim
  namespace: torrent
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "rutorrent-torrent"
  resources:
    requests:
      storage: 2000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rutorrent-config-claim
  namespace: torrent
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "rutorrent-config"
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
  namespace: torrent
  labels:
    app: rutorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      volumes:
      - name: goose-credentials-volume
        secret:
          secretName: goose
          items:
          - key: login.conf
            path: login.conf
          defaultMode: 0600
      - name: set-goose-ovpn-volume
        secret:
          secretName: goose
          items:
          - key: ro-10.ovpn
            path: ro-10.ovpn
          defaultMode: 0744
      - name: set-goose-config-volume
        configMap:
          name: set-goose
          items:
          - key: set-goose.sh
            path: set-goose.sh
          defaultMode: 0744
      - name: torrent
        persistentVolumeClaim:
          claimName: rutorrent-torrent-claim
      - name: config
        persistentVolumeClaim:
          claimName: rutorrent-config-claim
      containers:
      - name: rutorrent
        image:  linuxserver/rutorrent
        # command: [ "/init"]
        command: [ "/goose/set-goose.sh"]
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        ports:
        - name: http
          containerPort: 80
        - name: scgi
          containerPort: 5000
        - name: bittorent
          containerPort: 31219
        - name: bittorent2
          containerPort: 6881
          protocol: UDP
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          # - mountPath: /dev/snd
          #   name: dev-snd
          - name: torrent
            mountPath: /downloads
          - name: config
            mountPath: /config
          - name: set-goose-config-volume
            mountPath: /goose/set-goose.sh
            subPath: set-goose.sh
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/ro-10.ovpn
            subPath: ro-10.ovpn
          - name: goose-credentials-volume
            mountPath: /etc/openvpn/login.conf
            subPath: login.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rutorrent
  name: rutorrent
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: rutorrent
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rutorrentingress
  namespace: torrent
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: torrent.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: rutorrent
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: uploadport-rutorrent
spec:
  type: NodePort
  ports:
    - port: 31219
      nodePort: 31219
  selector:
    name: rutorrent          