apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- homeassistant-pv.yml
- homeassistant-pvc.yml
- z2m-pv.yml
- z2m-pvc.yml
- otbr-pv.yml
- otbr-pvc.yml
- matter-server-pv.yml
- matter-server-pvc.yml

