---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-claim
  namespace: torrent
spec:
  storageClassName: ssh-na
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-claim
  namespace: torrent
spec:
  storageClassName: ssd-na
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-claim
  namespace: torrent
spec:
  storageClassName: ssd-ha
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi