---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cloud-backup-tmp-data-pv
  labels:
    contenttype: "cloud-backup-tmp-data"
spec:
  capacity:
    storage: 10Gi
  storageClassName: cloud-backup-tmp-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd/tmp/cloud-backup-tmp"