---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-backup-tmp-data-claim
spec:
  storageClassName: cloud-backup-tmp-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-backup-media-data-claim
spec:
  storageClassName: cloud-backup-media-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
