---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-data-pv
  labels:
    contenttype: "prometheus-data"
spec:
  capacity:
    storage: 10Gi
  storageClassName: prometheus-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/prometheus/data" # path to directory