---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: essential-workingdir-claim
spec:
  storageClassName: essential-workingdir
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi