---
- name: Remote-cube backup / Deploy the backup script
  become: yes
  template:
    src: seb-backup-script.sh.j2
    dest: /root/seb-backup-script.sh
    owner: root
    group: root
    mode: '0755'

- name: Remote-cube backup / create crontab
  become: yes
  cron:
    name: "Weekly Backup at Sunday 2am of /mnt/ folders from jay-c to remote-cube every week"
    minute: "0"      # Run at the top of the hour
    hour: "2"        # Run at 2 AM
    day: "7"         # Run on Sundays (day 7 of the week)
    job: "/bin/bash /root/seb-backup-script.sh"
    state: present