---
- name: Remote-cube backup / Install Samba
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cifs-utils 

- name: Remote-cube backup / Create mount folder
  become: yes
  ansible.builtin.file:
    path: /mnt/jay-c/media/bas
    state: directory
  async: 5          # Set the timeout to 5 seconds
  poll: 1           # Wait for the task to complete, but timeout after 5 seconds
  ignore_errors: yes  # Ignore errors and continue execution if it fails or times out

- name: Remote-cube backup / Ensure the .samba directory exists\
  become: yes
  file:
    path: /home/basraven/.samba
    state: directory
    owner: basraven
    group: basraven
    mode: '0700'

- name: Remote-cube backup / Load Samba credentials
  include_vars:
    file: ../../credentials/samba/samba-credentials.yml

- name: Get the password for basraven
  set_fact:
    samba_password: "{{ samba_users | selectattr('name', 'equalto', 'basraven') | map(attribute='passwd') | first }}"

- name: Remote-cube backup / Create the Samba credentials file
  become: yes
  copy:
    dest: /home/basraven/.samba/credentials
    content: |
      username=basraven
      password={{ samba_password }}
      domain=WORKGROUP
    owner: basraven
    group: basraven
    mode: '0600'

- name: Remote-cube backup / Add to fstab
  become: yes
  lineinfile:
    path: /etc/fstab
    line: "//10.8.0.1/basraven /mnt/jay-c/media/bas cifs credentials=/home/basraven/.samba/credentials,iocharset=utf8,vers=3.0,ro" # read-only
    # line: "//10.8.0.1/basraven /mnt/jay-c/media/bas cifs credentials=/home/basraven/.samba/credentials,iocharset=utf8,vers=3.0 0 0"
    state: present
    create: yes
    backup: yes

# - name: Remote-cube backup / Mount the Samba share
#   become: yes
#   command: mount -a
#   args:
#     warn: false

## Make sure the network connection is established 

- name: Remote-cube backup / Create the systemd directory for remote-fs.target overrides if it doesn't exist
  become: yes
  file:
    path: /etc/systemd/system/remote-fs.target.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Remote-cube backup / Create override configuration for remote-fs.target to wait for tun0
  become: yes
  copy:
    dest: /etc/systemd/system/remote-fs.target.d/override.conf
    content: |
      [Unit]
      After=network-online.target
      Wants=network-online.target
      After=network.target
      Requires=tun0.network
    owner: root
    group: root
    mode: '0644'

- name: Remote-cube backup / Create systemd network configuration for tun0
  become: yes
  copy:
    dest: /etc/systemd/network/tun0.network
    content: |
      [Match]
      Name=tun0

      [Network]
      DHCP=yes
    owner: root
    group: root
    mode: '0644'

- name: Remote-cube backup / Reload systemd daemon and networkd
  become: yes
  command: systemctl daemon-reload

- name: Remote-cube backup / Restart systemd-networkd
  become: yes
  command: systemctl restart systemd-networkd

- name: Remote-cube backup / Ensure remote-fs.target waits for tun0
  become: yes
  systemd:
    name: remote-fs.target
    enabled: yes