---
- name: Remote-cube backup / Install Samba and netcat (for ping)
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cifs-utils 
    - netcat-openbsd

- name: Remote-cube backup / Create mount folders
  become: yes
  ansible.builtin.file:
    path: /mnt/jayc/{{ item }}
    state: directory
  async: 5          # Set the timeout to 5 seconds
  poll: 1           # Wait for the task to complete, but timeout after 5 seconds
  ignore_errors: yes  # Ignore errors and continue execution if it fails or times out
  with_items: "{{ source_directories }}"

- name: Remote-cube backup / Create target folders
  become: yes
  ansible.builtin.file:
    path: /mnt/hdd/backup/{{ item }}
    state: directory
  async: 5          # Set the timeout to 5 seconds
  poll: 1           # Wait for the task to complete, but timeout after 5 seconds
  ignore_errors: yes  # Ignore errors and continue execution if it fails or times out
  with_items: "{{ source_directories }}"

- name: Remote-cube backup / Ensure the .samba directory exists
  become: yes
  file:
    path: /home/basraven/.samba
    state: directory
    owner: basraven
    group: basraven
    mode: '0700'

- name: Remote-cube backup / Load Samba credentials
  include_vars:
    file: ../../credentials/samba/samba-credentials.yml

- name: Get the password for sebackup
  set_fact:
    samba_password: "{{ samba_users | selectattr('name', 'equalto', 'sebackup') | map(attribute='passwd') | first }}"

- name: Remote-cube backup / Create the Samba credentials file
  become: yes
  copy:
    dest: /home/basraven/.samba/credentials
    content: |
      username=sebackup
      password={{ samba_password }}
      domain=WORKGROUP
    owner: basraven
    group: basraven
    mode: '0600'

- name: Remote-cube backup / Create systemd mount unit for remote filesystems
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/system/mnt-jayc-{{ item | replace('/', '-') }}.mount
    content: |
      [Unit]
      Description=Mount remote filesystem /mnt/jayc/{{ item }}
      After=network-online.target

      [Mount]
      What=//10.8.0.1/{{ item | replace('/', '-') }}
      Where=/mnt/jayc/{{ item }}
      Type=cifs
      Options=credentials=/home/basraven/.samba/credentials,iocharset=utf8,vers=3.0,ro
      TimeoutSec=20

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ source_directories }}"

- name: Remote-cube backup / Reload systemd to pick up the new mount units
  become: yes
  systemd:
    daemon_reload: yes

- name: Remote-cube backup / Enable the mount units to start at boot
  become: yes
  systemd:
    name: mnt-jayc-{{ item | replace('/', '-') }}.mount
    enabled: yes
  with_items: "{{ source_directories }}"

- name: Remote-cube backup / Start the mount units
  become: yes
  systemd:
    name: mnt-jayc-{{ item | replace('/', '-') }}.mount
    state: started
  with_items: "{{ source_directories }}"
