---
- name: Remote-cube backup / Install Samba and netcat (for ping)
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cifs-utils 
    - netcat-openbsd

- name: Remote-cube backup / Create mount folder
  become: yes
  ansible.builtin.file:
    path: /mnt/jayc/media/bas
    state: directory
  async: 5          # Set the timeout to 5 seconds
  poll: 1           # Wait for the task to complete, but timeout after 5 seconds
  ignore_errors: yes  # Ignore errors and continue execution if it fails or times out

- name: Remote-cube backup / Ensure the .samba directory exists
  become: yes
  file:
    path: /home/basraven/.samba
    state: directory
    owner: basraven
    group: basraven
    mode: '0700'

- name: Remote-cube backup / Load Samba credentials
  include_vars:
    file: ../../credentials/samba/samba-credentials.yml

- name: Get the password for basraven
  set_fact:
    samba_password: "{{ samba_users | selectattr('name', 'equalto', 'basraven') | map(attribute='passwd') | first }}"

- name: Remote-cube backup / Create the Samba credentials file
  become: yes
  copy:
    dest: /home/basraven/.samba/credentials
    content: |
      username=basraven
      password={{ samba_password }}
      domain=WORKGROUP
    owner: basraven
    group: basraven
    mode: '0600'

- name: Remote-cube backup / Create systemd mount unit for remote filesystem
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/system/mnt-jayc-media-bas.mount
    content: |
      [Unit]
      Description=Mount remote filesystem /mnt/jayc/media/bas
      After=network-online.target

      [Mount]
      What=//10.8.0.1/basraven
      Where=/mnt/jayc/media/bas
      Type=cifs
      Options=credentials=/home/basraven/.samba/credentials,iocharset=utf8,vers=3.0,ro
      TimeoutSec=20

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Remote-cube backup / Reload systemd to pick up the new mount unit
  become: yes
  systemd:
    daemon_reload: yes

- name: Remote-cube backup / Enable the mount unit to start at boot
  become: yes
  systemd:
    name: mnt-jayc-media-bas.mount
    enabled: yes

- name: Remote-cube backup / Start the mount unit
  become: yes
  systemd:
    name: mnt-jayc-media-bas.mount
    state: started

- name: Remote-cube backup / Check status of the mount unit
  become: yes
  command: systemctl status mnt-jayc-media-bas.mount
  register: mount_status
  changed_when: false

- name: Remote-cube backup / Display the mount unit status
  debug:
    msg: "{{ mount_status.stdout }}"