---
- name: Dnsmasq / Install dnsmasq
  become: yes
  package:
    name: dnsmasq
    state: present
- name: Dnsmasq / Place config
  become: yes
  template:
    src: "../templates/dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    mode: "0755"
- name: Dnsmasq / Create await dir
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    force: yes
    recurse: yes
  with_items:
    - "/etc/systemd/system/dnsmasq.service.d"
- name: Dnsmasq / Await openvpn
  become: yes
  template:
    src: "../templates/dnsmasq-systemd-override.conf"
    dest: "/etc/systemd/system/dnsmasq.service.d/override.conf"
    mode: "0755"
- name: Dnsmasq / Update /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^10.8.0.1'
    line: "10.8.0.1 *.bas"
    state: present
    backup: yes
  notify:
    - restart dnsmasq