apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: weekly-jackett-cloud-backup
spec:
  schedule: "30 12 * * 0" # Every Sunday at 12:30 AM
  concurrencyPolicy: "Forbid"
  timezone: "Europe/Amsterdam"
  workflowSpec:
    workflowTemplateRef:
      name: nonessential-cloud-backup
    arguments:
      parameters:
        - name: appname
          value: "jackett"
        - name: localpath
          value: "/mnt/ssd/na/jackett-config"
