apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cron-weekly-jackett-cloud-backup.yml
- cron-weekly-jellyseerr-cloud-backup.yml
- cron-weekly-radarr-cloud-backup.yml
- cron-weekly-sonarr-cloud-backup.yml
- cron-weekly-grafana-cloud-backup.yml
- cron-weekly-prometheus-cloud-backup.yml
- cron-weekly-monica-cloud-backup.yml
- cron-weekly-homeassistant-cloud-backup.yml
