---
- name: Create User / Check input variable
  fail: 
    msg: "Variable '{{ item }}' is not defined"
  when: item not in hostvars[inventory_hostname]
  with_items:
    - openvpn_user

- name: Create User / Install expect if needed
  become: yes
  package: 
    name: expect
    state: present

- name: Create User / Easyrsa build-client-full
  become: yes
  shell: |
    export EASYRSA_BATCH=1 # non-interactive mode
    ./easyrsa build-client-full {{ openvpn_user }} nopass
  args:
    chdir: "{{ openvpn_ca_dir }}"
    executable: /bin/bash

- name: "Create User / Create {{ openvpn_client_configs_dir }}"
  become: yes
  file:
    path: "{{ openvpn_client_configs_dir }}"
    state: directory
    mode: 0644
    recurse: yes

- name: "Create User / establish base.client.conf.j2 template in {{ openvpn_client_configs_dir }}/{{ openvpn_user }}.ovpn"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - { src: base.client.conf.j2, dest:  "{{ openvpn_client_configs_dir }}/{{ openvpn_user }}.ovpn" }

# Based on: https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_getclient
- name: Create User / Build .ovpn cert
  become: yes
  shell: |
    echo "
    <key>
    $(cat pki/private/{{openvpn_user}}.key)
    </key>
    <cert>
    $(openssl x509 -in pki/issued/{{openvpn_user}}.crt)
    </cert>
    <ca>
    $(cat pki/ca.crt)
    </ca>
    <tls-auth>
    $(cat pki/ta.key)
    </tls-auth>
    " >> {{ openvpn_client_configs_dir }}/{{ openvpn_user }}.ovpn
  args:
    chdir: "{{ openvpn_ca_dir }}"
    executable: /bin/bash

- name: Create User / Copying {{ openvpn_user }}.ovpn to ../../credentials/ovpn/{{ openvpn_user }}.ovpn
  become: yes
  fetch:
    src: "{{ openvpn_client_configs_dir }}/{{ openvpn_user }}.ovpn"
    dest: ../../credentials/ovpn/{{ openvpn_user }}.ovpn
    flat: True