---
- name: Fail2Ban / Copy openvpn jail filter script
  become: yes
  template: 
    src: fail2ban.filter.openvpn.local.j2
    dest: /etc/fail2ban/filter.d/openvpn.local
    mode: "0755"

- name: Fail2Ban / Copy openvpn jail script
  become: yes
  template: 
    src: fail2ban.jail.openvpn.j2
    dest: /etc/fail2ban/jail.d/openvpn
    mode: "0755"