---
- hosts: all
  remote_user: root
  vars: 
    ansible_ssh_pass: raspberry
    ansible_host_key_checking: False 
  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/credentials/ssh/id_rsa.pub') }}"