---
- include_tasks: install-x11.yml
  tags: kiosk

- include_tasks: install-browser.yml
  tags: kiosk

- include_tasks: configure-autologin.yml
  tags: kiosk

- include_tasks: configure-x11-kiosk.yml
  tags: kiosk

- include_tasks: install-nginx.yml
  tags: kiosk

- include_tasks: build-spa-local.yml
  tags: kiosk

- include_tasks: deploy-spa.yml
  tags: kiosk