# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: torrent-config-claim
#   namespace: torrent
# spec:
#   storageClassName: torrent-config
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-standard-data-claim
  namespace: torrent
spec:
  storageClassName: torrent-standard-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-series-data-claim
  namespace: torrent
spec:
  storageClassName: torrent-series-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-uhd-data-claim
  namespace: torrent
spec:
  storageClassName: torrent-uhd-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-torrent-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qbit-torrent-data
  selector:
    matchLabels:
      contenttype: "qbit-torrent-data"
  resources:
    requests:
      storage: 2000Gi
      