---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-standard-data-claim
  namespace: torrent
spec:
  storageClassName: torrent-standard-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-torrent-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qbit-torrent-data
  selector:
    matchLabels:
      contenttype: "qbit-torrent-data"
  resources:
    requests:
      storage: 2000Gi
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-torrent-ssd-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qbit-torrent-ssd-data
  selector:
    matchLabels:
      contenttype: "qbit-torrent-ssd-data"
  resources:
    requests:
      storage: 200Gi
      