---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-data-pv
  labels:
    contenttype: "torrent-data"
spec:
  capacity:
    storage: 2000Gi
  storageClassName: torrent-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.5.100 # ip addres of nfs server
    path: "/mnt/hdd/na/torrent" # path to directory
