---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-standard-data-pv
  labels:
    contenttype: "torrent-standard-data"
spec:
  capacity:
    storage: 1Gi
  storageClassName: torrent-standard-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/torrent/state/standard"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-series-data-pv
  labels:
    contenttype: "torrent-series-data"
spec:
  capacity:
    storage: 1Gi
  storageClassName: torrent-series-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/torrent/state/series"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-uhd-data-pv
  labels:
    contenttype: "torrent-uhd-data"
spec:
  capacity:
    storage: 1Gi
  storageClassName: torrent-uhd-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/torrent/state/uhd"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: qbit-torrent-data-pv
  labels:
    contenttype: "qbit-torrent-data"
spec:
  capacity:
    storage: 2000Gi
  storageClassName: qbit-torrent-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/hdd/torrent" # path to directory
