---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-standard-data-pv
  labels:
    contenttype: "torrent-standard-data"
spec:
  capacity:
    storage: 1Gi
  storageClassName: torrent-standard-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/torrent/state/standard"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: qbit-torrent-data-pv
  labels:
    contenttype: "qbit-torrent-data"
spec:
  capacity:
    storage: 2000Gi
  storageClassName: qbit-torrent-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/hdd/torrent" # path to directory

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: qbit-torrent-ssd-data-pv
  labels:
    contenttype: "qbit-torrent-ssd-data"
spec:
  capacity:
    storage: 200Gi
  storageClassName: qbit-torrent-ssd-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/torrent-ssd" # path to directory
