---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-data-claim
  namespace: crm
spec:
  storageClassName: monica-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-database-claim
  namespace: crm
spec:
  storageClassName: monica-database
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
