---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: torrent
data:
  set-goose.sh: |-
    #!/bin/sh
    set -eu
    apt-get update
    apt-get install openvpn -y
    nohup openvpn /etc/openvpn/cert3.conf &
    # echo AUTOSTART="all" >> /etc/default/openvpn
    # echo "sleeping 15 secs..."
    # sleep 15
    # echo "Finished sleeping 15 secs"
    # ip route del 0.0.0.0/1 | true # TODO: TEMPFIX
    # echo "[OPENVPN] Creating GooseVPN connection"
    # /init
    sleep 10000
  
  update-resolv-conf: |-
    #!/bin/bash
    #
    # Parses DHCP options from openvpn to update resolv.conf
    # To use set as 'up' and 'down' script in your openvpn *.conf:
    # up /etc/openvpn/update-resolv-conf
    # down /etc/openvpn/update-resolv-conf
    #
    # Used snippets of resolvconf script by Thomas Hood and Chris Hanson.
    # Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL.
    #
    # Example envs set from openvpn:
    #
    #     foreign_option_1='dhcp-option DNS 193.43.27.132'
    #     foreign_option_2='dhcp-option DNS 193.43.27.133'
    #     foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
    #

    # bash -c "sleep 5 && echo 'removing 0000 route' && ip route del 0.0.0.0/1 | true" &

    [ -x /sbin/resolvconf ] || exit 0
    [ "$script_type" ] || exit 0
    [ "$dev" ] || exit 0

    split_into_parts()
    {
            part1="$1"
            part2="$2"
            part3="$3"
    }

    case "$script_type" in
      up)
            NMSRVRS=""
            SRCHS=""
            for optionvarname in ${!foreign_option_*} ; do
                    option="${!optionvarname}"
                    echo "$option"
                    split_into_parts $option
                    if [ "$part1" = "dhcp-option" ] ; then
                            if [ "$part2" = "DNS" ] ; then
                                    NMSRVRS="${NMSRVRS:+$NMSRVRS }$part3"
                            elif [ "$part2" = "DOMAIN" ] ; then
                                    SRCHS="${SRCHS:+$SRCHS }$part3"
                            fi
                    fi
            done
            R=""
            [ "$SRCHS" ] && R="search $SRCHS
    "
            for NS in $NMSRVRS ; do
                    R="${R}nameserver $NS
    "
            done
            echo -n "$R" | /sbin/resolvconf -a "${dev}.openvpn"
            ;;
      down)
            /sbin/resolvconf -d "${dev}.openvpn"
            ;;
    esac
   
  
  qBittorrent.conf: |-
    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    Session\Categories=@Variant(\0\0\0\b\0\0\0\x2\0\0\0\f\0s\0\x65\0r\0i\0\x65\0s\0\0\0\n\0\0\0\"\0/\0\x64\0o\0w\0n\0l\0o\0\x61\0\x64\0s\0/\0s\0\x65\0r\0i\0\x65\0s\0\0\0\f\0m\0o\0v\0i\0\x65\0s\0\0\0\n\0\0\0\"\0/\0\x64\0o\0w\0n\0l\0o\0\x61\0\x64\0s\0/\0m\0o\0v\0i\0\x65\0s)
    Session\CreateTorrentSubfolder=true
    Session\DisableAutoTMMByDefault=false
    Session\DisableAutoTMMTriggers\CategoryChanged=false
    Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
    Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [LegalNotice]
    Accepted=true

    [Preferences]
    Bittorrent\AddTrackers=false
    Bittorrent\MaxRatioAction=0
    Bittorrent\PeX=true
    Connection\GlobalDLLimitAlt=10
    Connection\GlobalUPLimitAlt=10
    Connection\Interface=tun0
    Connection\PortRangeMin=6881
    Connection\UPnP=false
    Downloads\PreAllocation=true
    Downloads\SavePath=/downloads/
    Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
    Downloads\StartInPause=false
    Downloads\TempPath=/downloads/incomplete/
    Downloads\UseIncompleteExtension=true
    DynDNS\DomainName=changeme.dyndns.org
    DynDNS\Enabled=false
    DynDNS\Password=
    DynDNS\Service=0
    DynDNS\Username=
    General\Locale=
    General\UseRandomPort=false
    MailNotification\email=
    MailNotification\enabled=false
    MailNotification\password=adminadmin
    MailNotification\req_auth=true
    MailNotification\req_ssl=false
    MailNotification\sender=qBittorrent_notification@example.com
    MailNotification\smtp_server=smtp.changeme.com
    MailNotification\username=admin
    Queueing\QueueingEnabled=false
    WebUI\Address=*
    WebUI\AlternativeUIEnabled=false
    WebUI\AuthSubnetWhitelist=0.0.0.0/32, 0.0.0.0/0
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\CSRFProtection=true
    WebUI\ClickjackingProtection=true
    WebUI\HTTPS\Enabled=false
    WebUI\HostHeaderValidation=true
    WebUI\LocalHostAuth=false
    WebUI\Port=8080
    WebUI\RootFolder=
    WebUI\ServerDomains=*
    WebUI\UseUPnP=true
    WebUI\Username=admin
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: torrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
      - name: goose-credentials-volume
        secret:
          secretName: goose-credentials
          items:
          - key: login.conf
            path: login.conf
          defaultMode: 0600
      - name: set-goose-ovpn-volume
        secret:
          secretName: goose-credentials
          items:
          - key: cert1.conf
            path: cert1.conf
          - key: cert2.conf
            path: cert2.conf
          - key: cert3.conf
            path: cert3.conf
          defaultMode: 0744
      
      - name: update-resolv-conf
        configMap:
          name: qbittorrent-config
          items:
          - key: update-resolv-conf
            path: update-resolv-conf-custom
          defaultMode: 0777
      - name: qbittorrent-config-client
        configMap:
          name: qbittorrent-config
          items:
          - key: qBittorrent.conf
            path: qBittorrent.conf
          defaultMode: 0744
      - name: qbittorrent-config-goose
        configMap:
          name: qbittorrent-config
          items:
          - key: set-goose.sh
            path: set-goose.sh
          defaultMode: 0744
      
      - name: torrent-volume
        persistentVolumeClaim:
          claimName: torrent-data-claim
      - name: qbittorrent-state
        persistentVolumeClaim:
          claimName: qbittorrent-state-claim
      containers:
      - name: qbittorrent
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 3
          failureThreshold: 3
          exec:
            command:
              - /bin/sh
              - -c
              - 'curl --connect-timeout 3 --max-time 5 -IsLX GET google.com:80 | grep 200'
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 3
          failureThreshold: 3
          exec:
            command:
              - /bin/sh
              - -c
              - 'curl --connect-timeout 3 --max-time 5 -IsLX GET google.com:80 | grep 200'
        resources: {}
        #   limits:
        #     memory: 300Mi
        #     cpu: 100m
        image: linuxserver/qbittorrent
        command: [ "/goose/set-goose.sh"]
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        ports:
        - name: http
          containerPort: 8080
        - name: bittorrent-port
          containerPort: 6881
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: WEBUI_PORT
          value: "8080"
        volumeMounts:
          - name: torrent-volume
            mountPath: /downloads
          - name: qbittorrent-config-client
            mountPath: /config/qBittorrent/qBittorrent.conf
            subPath: qBittorrent.conf
          - name: update-resolv-conf
            mountPath: /etc/openvpn/update-resolv-conf-custom
            subPath: update-resolv-conf-custom
          - name: qbittorrent-config-goose
            mountPath: /goose/set-goose.sh
            subPath: set-goose.sh
          - name: qbittorrent-state
            mountPath: /config
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/cert1.conf
            subPath: cert1.conf
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/cert2.conf
            subPath: cert2.conf
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/cert3.conf
            subPath: cert3.conf
          - name: goose-credentials-volume
            mountPath: /goose/login.conf
            subPath: login.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: qbittorrent
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: qbittorrentingress
  namespace: torrent
spec:
  rules:
  - host: torrent.bas
    http:
      paths:
      - backend:
          serviceName: qbittorrent
          servicePort: 80
  # tls:
  # - hosts:
  #   - torrent.bas


---
apiVersion: v1
kind: Service
metadata:
  name: qbittorent-lb-service
  namespace: torrent
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: qbittorrent
  type: LoadBalancer
  loadBalancerIP: 192.168.6.61