---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: torrent
data:
  set-goose.sh: |-
    #!/bin/sh
    set -eu
    apt-get update
    apt-get install openvpn iputils-ping net-tools curl  jq -y
    sysctl net.ipv4.ip_forward=1
    echo "## Installs complete"
    /usr/sbin/openvpn /etc/openvpn/cert2.conf   &
    sleep infinity


  run-qbittorrent.sh: |-
    #!/bin/sh
    set -eu
    apt-get update
    apt-get install iputils-ping net-tools curl jq -y
    sysctl net.ipv4.ip_forward=1
    SLEEPTIME=40
    echo "## Sleeping $SLEEPTIME secs..."
    sleep $SLEEPTIME
    /init
 
  vpn-delete-route.sh: |-
    #!/bin/sh
    echo "## In VPN DELETE ROUTE"
    export VPN_GATEWAY=$(route -n | awk 'NR==3' | awk '{ print $2 }')
    nohup bash -c "sleep 3 && echo 'Deleting $VPN_GATEWAY' && ip route del 0.0.0.0/1 via $VPN_GATEWAY && curl ipinfo.io && echo '## Finished delete route' "&
    nohup bash -c "sleep 2 && ip route add 10.244.0.0/16 via 169.254.1.1 dev eth0" &
  
  qBittorrent.conf: |-
    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    Session\Categories=@Variant(\0\0\0\b\0\0\0\x2\0\0\0\f\0s\0\x65\0r\0i\0\x65\0s\0\0\0\n\0\0\0\"\0/\0\x64\0o\0w\0n\0l\0o\0\x61\0\x64\0s\0/\0s\0\x65\0r\0i\0\x65\0s\0\0\0\f\0m\0o\0v\0i\0\x65\0s\0\0\0\n\0\0\0\"\0/\0\x64\0o\0w\0n\0l\0o\0\x61\0\x64\0s\0/\0m\0o\0v\0i\0\x65\0s)
    Session\CreateTorrentSubfolder=true
    Session\DisableAutoTMMByDefault=false
    Session\DisableAutoTMMTriggers\CategoryChanged=false
    Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
    Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false

    [Core]
    AutoDeleteAddedTorrentFile=Never

    [LegalNotice]
    Accepted=true

    [Preferences]
    Bittorrent\AddTrackers=false
    Bittorrent\MaxRatioAction=0
    Bittorrent\PeX=true
    Connection\GlobalDLLimitAlt=10
    Connection\GlobalUPLimitAlt=10
    Connection\Interface=tun0
    Connection\PortRangeMin=6881
    Connection\UPnP=false
    Downloads\PreAllocation=true
    Downloads\SavePath=/downloads/
    Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
    Downloads\StartInPause=false
    Downloads\TempPath=/downloads/incomplete/
    Downloads\UseIncompleteExtension=true
    DynDNS\DomainName=changeme.dyndns.org
    DynDNS\Enabled=false
    DynDNS\Password=
    DynDNS\Service=0
    DynDNS\Username=
    General\Locale=
    General\UseRandomPort=false
    MailNotification\email=
    MailNotification\enabled=false
    MailNotification\password=adminadmin
    MailNotification\req_auth=true
    MailNotification\req_ssl=false
    MailNotification\sender=qBittorrent_notification@example.com
    MailNotification\smtp_server=smtp.changeme.com
    MailNotification\username=admin
    Queueing\QueueingEnabled=false
    WebUI\Address=*
    WebUI\AlternativeUIEnabled=false
    WebUI\AuthSubnetWhitelist=0.0.0.0/32, 0.0.0.0/0
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\CSRFProtection=true
    WebUI\ClickjackingProtection=true
    WebUI\HTTPS\Enabled=false
    WebUI\HostHeaderValidation=true
    WebUI\LocalHostAuth=false
    WebUI\Port=8080
    WebUI\RootFolder=
    WebUI\ServerDomains=*
    WebUI\UseUPnP=true
    WebUI\Username=admin
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: torrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      # TODO: Only works on that node for some reason...
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution :
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - linux-wayne
      dnsConfig:
        # Not sure if this is really needed...
        nameservers:
          - 8.8.8.8
      dnsPolicy: None
      volumes:
      - name: goose-credentials-volume
        secret:
          secretName: goose-credentials
          items:
          - key: login.conf
            path: login.conf
          defaultMode: 0600
      - name: set-goose-ovpn-volume
        secret:
          secretName: goose-credentials
          items:
          - key: cert1.conf
            path: cert1.conf
          - key: cert2.conf
            path: cert2.conf
          - key: cert3.conf
            path: cert3.conf
          defaultMode: 0744
      - name: update-resolv-conf
        configMap:
          name: qbittorrent-config
          items:
          - key: update-resolv-conf
            path: update-resolv-conf-custom
          defaultMode: 0777
      - name: qbittorrent-config-client
        configMap:
          name: qbittorrent-config
          items:
          - key: qBittorrent.conf
            path: qBittorrent.conf
          defaultMode: 0744
      - name: qbittorrent-config-goose
        configMap:
          name: qbittorrent-config
          items:
          - key: set-goose.sh
            path: set-goose.sh
          defaultMode: 0744
      - name: qbittorrent-config-qbit
        configMap:
          name: qbittorrent-config
          items:
          - key: run-qbittorrent.sh
            path: run-qbittorrent.sh
          defaultMode: 0744
      
      - name: vpn-delete-route
        configMap:
          name: qbittorrent-config
          items:
          - key: vpn-delete-route.sh
            path: vpn-delete-route.sh
          defaultMode: 0744
      
      - name: torrent-volume
        persistentVolumeClaim:
          claimName: torrent-data-claim
      - name: qbittorrent-state
        persistentVolumeClaim:
          claimName: qbittorrent-state-claim

      containers:
      - name: vpn
        resources: 
          limits:
            memory: "2056Mi"
            cpu: "2000m"
        image: ubuntu
        command: [ "/goose/set-goose.sh"]
        stdin: true
        tty: true
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: qbittorrent-config-goose
            mountPath: /goose/set-goose.sh
            subPath: set-goose.sh
          - name: vpn-delete-route
            mountPath: /goose/vpn-delete-route.sh
            subPath: vpn-delete-route.sh
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/cert1.conf
            subPath: cert1.conf
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/cert2.conf
            subPath: cert2.conf
          - name: set-goose-ovpn-volume
            mountPath: /etc/openvpn/cert3.conf
            subPath: cert3.conf
          - name: goose-credentials-volume
            mountPath: /goose/login.conf
            subPath: login.conf
      - name: qbit
        # livenessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 20
        #   failureThreshold: 5
        #   exec:
        #     command:
        #       - /bin/sh
        #       - -c
        #       - 'curl ipinfo.io |  jq -r ".timezone" |  grep "Europe/Budapest"'
        # readinessProbe:
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   failureThreshold: 5
        #   exec:
        #     command:
        #       - /bin/sh
        #       - -c
        #       - 'curl ipinfo.io |  jq -r ".timezone" |  grep "Europe/Budapest"'
        resources: 
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2056Mi"
            cpu: "2000m"
        image: linuxserver/qbittorrent
        command: [ "/goose/run-qbittorrent.sh"]
        stdin: true
        tty: true
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        ports:
        - name: http
          containerPort: 8080
        - name: bittorrent-port
          containerPort: 30163
          protocol: UDP
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: WEBUI_PORT
          value: "8080"
        volumeMounts:
          - name: torrent-volume
            mountPath: /downloads
          - name: qbittorrent-config-client
            mountPath: /config/qBittorrent/qBittorrent.conf
            subPath: qBittorrent.conf
          - name: qbittorrent-config-qbit
            mountPath: /goose/run-qbittorrent.sh
            subPath: run-qbittorrent.sh
          - name: qbittorrent-state
            mountPath: /config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: qbittorrent
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrentingress
  namespace: torrent
spec:
  rules:
  - host: torrent.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              number: 80
  # tls:
  # - hosts:
  #   - torrent.bas



---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-lb-service
  namespace: torrent
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: qbittorrent
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.6.61
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-lb-torrent-service
  namespace: torrent
spec:
  ports:
  - name: bittorrent-port
    port: 30163
    targetPort: 30163
    protocol: UDP
    nodePort: 30163
  selector:
    app: qbittorrent
  type: NodePort
  # externalTrafficPolicy: Local
  # loadBalancerIP: 192.168.6.71