---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
  namespace: monitoring
spec:
  storageClassName: nfs-112
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi