---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-push-gateway-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-212
  resources:
    requests:
      storage: 2Gi