---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-ro-nonessential-claim
spec:
  storageClassName: hdd-ro-nonessential
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
