apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ssd-ro-nonessential-pv.yml
- ssd-ro-nonessential-pvc.yml
- hdd-ro-nonessential-pv.yml
- hdd-ro-nonessential-pvc.yml
- nonessential-workingdir-pv.yml
- nonessential-workingdir-pvc.yml