---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-ro-nonessential-claim
spec:
  storageClassName: ssd-ro-nonessential
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
