---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-apps-to-access-traefik # not tested yet
  namespace:  online
spec:
  podSelector: 
    matchLabels:
      app: status
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: online-traefik-ingress-lb
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-status-to-access-plusone # not working yet
  namespace:  plusone
spec:
  podSelector: 
    matchLabels:
      app: statusplusone
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          plusone: access
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-vpn-to-access-plusone # not working yet
  namespace:  plusone
spec:
  podSelector: 
    matchLabels:
      app: openvpn
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          plusone: access
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: online
spec:
  podSelector: {}
  policyTypes:
  - Egress
