---
- hosts: linux-wayne
  roles:
  - define-os # Should always run!
  # - hostname
  # - avahi

  # - users
  # - update
  # - ssh
  # - security
  # - reboot
  # - nfs
  # - samba
  # - containerd
  # - haproxy
  # - kubernetes-install
  - kubernetes-init
  - kubernetes-fetch
  
  # - backup

  # - dnsmasq
  # - openvpn-server
  