---
- hosts: linux-wayne
  roles:
  - define-os
  - hostname
  # - users
  # - security
  # - reboot
  # - dnsmasq
  # - nfs
  # - samba
  - containerd
  # - openvpn
  - haproxy
  - prometheus_node_exporter
  - kubernetes