---
- hosts: remote 
  roles:
  - define-os # Should always run!
  # - hostname
  # - users
  # - openvpn-client
  # - update
  # - ssh  
  - remote-cube-backup
  # - reboot
  # - prometheus_node_exporter
  # - toolbox
  # - reboot
  