---
- include: create-backup-user.yml
  tags:
    - nfs_server
    - nfs_client 
- include: nfs-common.yml
  tags: 
    - nfs_server
    - nfs_client 
- include: nfs-server.yml
  tags: nfs_server
# - include: nfs-client.yml
#   tags: nfs_client

