---
- include_tasks: create-backup-user.yml
  tags:
    - nfs_server
    - nfs_client 
- include_tasks: nfs-common.yml
  tags: 
    - nfs_server
    - nfs_client 
- include_tasks: nfs-server.yml
  tags: nfs_server
# - include_tasks: nfs-client.yml
#   tags: nfs_client

