---
# TODO: use pretty mapping here
- name: Nfs Common / Check if packages are installed non CentOS
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - nfs-kernel-server 
      - nfs-common
      - rpcbind
  when: ansible_facts['distribution'] != "CentOS"

- name: Nfs Common / Check if packages are installed CentOS
  become: yes
  package: 
    name: "{{ item }}"
    state: present
  with_items:
      - nfs-utils
      - rpcbind
  when: ansible_facts['distribution'] == "CentOS"
