---
- name: Nfs Folders / Make sure folder exists
  become: yes
  file:
    path: "{{ nfs_backup_folder_path }}"
    state: directory
    mode: '0777'

- name: Nfs Folders / Make sure folder exists
  become: yes
  file:
    path: "{{ nfs_backup_folder_path }}/.placeholder"
    state: touch
    mode: '0777'
