---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocd
  namespace: cicd
  labels:
    app: gocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocd
  template:
    metadata:
      labels:
        app: gocd
    spec:
      containers:
      - name: gocd
        image: gocd/gocd-server
        ports:
        - name: http
          containerPort: 8153
        # command: ["/bin/sh"]
        # args: ["-c", "sleep 1000000"]
          # - --nogui
          # - --server
          # - -e
          # - --gocdallgenres.fischvolk.de:22224
          # - --servername
          # - sebserver
          # - --port
          # - "80"
          # - --numchannels
          # - "16"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gocd
  name: gocd
  namespace: cicd
spec:
  ports:
  - name: http
    targetPort: 8153
    port: 80
  selector:
    app: gocd
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gocd
  namespace: cicd
spec:
  rules:
  - host: gocd.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: gocd
          servicePort: 80 