apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
configMapGenerator:
- name: install-tools
  files:
  - install-tools.sh
generatorOptions:
  disableNameSuffixHash: true
