---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: network
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:    
      containers:
      - name: email
        image: namshi/smtp
        ports:
        - name: smtp
          containerPort: 25
        env:
        - name: MAILNAME
          value: "admin.bas"
        - name: PORT 
          value: "25"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email
  name: email
  namespace: network
spec:
  ports:
  - name: smtp
    targetPort: 25
    port: 25
  selector:
    app: email
  type: ClusterIP
