---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
    - name: Init K8s
      command: kubeadm init --apiserver-advertise-address {{ ansible_default_ipv4.address }}
      # command: kubeadm init --token-ttl=0
      ignore_errors: yes
      async: 600
      poll: 5

    - file: 
        path: /root/.kube
        state: directory
        recurse: yes

    - name: copy admin.conf as default conf
      command: cp /etc/kubernetes/admin.conf /home/{{ target_user }}/.kube/config

    - name: chown config
      command: chown {{ target_user }}:{{ target_user }} /home/{{ target_user }}/.kube/config

    - fetch:
        src: /home/{{ target_user }}/.kube/config
        dest: /root/.kube/config
        flat: True

    - fetch:
        src: /home/{{ target_user }}/.kube/config
        dest: /credentials/kubernetes/
        flat: True

