---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
      - name: Init K8s
        # command: kubeadm init --pod-network-cidr=10.244.0.0/16 
        command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all --apiserver-advertise-address={{ ansible_default_ipv4.address }}
        # command: kubeadm init --token-ttl=0
        ignore_errors: yes
        async: 600
        poll: 5

        