---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
      - name: Check if apt-transport-https is installed
        apt: name={{item}} state=present
        with_items:
            - apt-transport-https
      - name: "add k8s key"
        shell:  'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -'
        args:
          executable: /bin/bash

      - name: "add k8s repo"
        shell:  'echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list'
        args:
          executable: /bin/bash
      - name: Update apt-get
        command: apt-get update -q 
        become: True
        
      - name: Install kubeadm
        command: apt-get install -yq kubelet kubeadm kubernetes-cni

      - name: Remove swap 1/2
        command: swapoff -a
        ignore_errors: yes
      
      # FIXME: automate with Ansible
      # MANUAL ACTION: prefix all swap in /etc/fstab with # (comment out)
      # - name: Remove swap 2/2
            
      - name: Reboot the host to reload the changed config
        shell: sleep 10 && /sbin/shutdown -r now 'Rebooting the host to reload the changed config'
        async: 15
        poll: 5
        ignore_errors: yes
      
      - name: Wait for system to become reachable again
        wait_for_connection:
            delay: 30
            timeout: 10
      # - name: "new method: kubeadm config images pull"
      #   shell:  'kubeadm config images pull'
      #   args:
      #     executable: /bin/bash
      - name: "allow kubernetes through ufw"
        shell:  'ufw allow 6443'
        args:
          executable: /bin/bash

        