---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
      - name: Reboot the host to reload the changed config
        shell: sleep 10 && /sbin/shutdown -r now 'Rebooting the host to reload the changed config'
        async: 15
        poll: 5
        ignore_errors: yes
      
      - name: Wait for system to become reachable again
        wait_for_connection:
            delay: 30
            timeout: 10
      - name: Include k8s join token
        include_vars:
          file: "{{credentials_dir}}/kubernetes/join-token.yaml"
      - name: Join K8s
        command: kubeadm join {{k8s_master_ip}}:6443 --token {{k8s_join_token}} --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=all
        ignore_errors: yes
        async: 600
        poll: 5

        