---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: nextcloud
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis-claim
      containers:
      - name: redis
        resources:
        image: redis:alpine
        ports:
        - containerPort: 6379        
        volumeMounts:
          - name: redis
            mountPath: "/data"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: nextcloud
spec:
  ports:
  - name: cache
    port: 6379
  selector:
    app: redis
  type: ClusterIP
