---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ollama
  selector:
    matchLabels:
      contenttype: "ollama"
  resources:
    requests:
      storage: 50Gi