---
- name: Fetch Kubeconfig / Fetch Kubernetes config file and put it in the local folder
  become: yes
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "~/.kube/config"
    flat: True
    force: yes