---
# Sources: 
  # Server install: https://help.ubuntu.com/community/Kerberos
  # NFSv4 config: https://help.ubuntu.com/community/NFSv4Howto
- name: Kerberos / Client & Server Install packages for (non) CentOS
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - { 'krb5-kdc' , when: "{{ kerberos == 'server' and ansible_facts['distribution'] != 'CentOS' }} "}
    - { 'krb5-libs', when: "{{ ansible_facts['distribution'] == 'CentOS' }} "}
# - name: Kerberos / Client & Server Install packages for CentOS
#   become: yes
#   package:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - krb5-libs
#     - krb5-workstation
#   when: ansible_facts['distribution'] == "CentOS"
  
# - name: Kerberos / Server Install packages for non CentOS
#   become: yes
#   package:
#     name: "{{ item }}"
#     state: present
#   when: 
#   with_items:
#     - krb5-admin-server

# - name: Kerberos / Server Install packages for CentOS
#   become: yes
#   package:
#     name: "{{ item }}"
#     state: present
#   when: kerberos == "server" and ansible_facts['distribution'] == "CentOS"
#   with_items:
#     - krb5-admin
#     - krb5-server
    

# - name: Kerberos / Change default (realm) config
#   become: yes
#   template:
#     src: kdc.conf.j2
#     dest: /etc/krb5kdc/kdc.conf
#     mode: "0755"