---
- name: UFW / Install UFW
  become: yes
  package:
    name: ufw
    state: present
- name: UFW / Enable UFW
  become: yes
  ufw:
    state: enabled
  when: '"qemu" not in group_names' # QEMU raspberry doesn't like this for some reason, not wasting time on this now, good luck future Seb (:

- name: UFW / Stop firewalld for CentOS, we are using ufw
  become: yes
  systemd:
    name: firewalld
    state: stopped
    force: yes
  when: ansible_facts['distribution'] == "CentOS"

- name: UFW / Disable firewalld for CentOS, we are using ufw
  become: yes
  systemd:
    name: firewalld
    enabled: no
    force: yes
  when: ansible_facts['distribution'] == "CentOS"
  
- name: UFW / Allow SSH
  become: yes
  ufw:
    rule: allow
    port: "22"
    proto: tcp
    
# - name: UFW / Rate Limit Ssh
#   become: yes
#   ufw:
#     rule: limit
#     port: "22"
#     proto: tcp

# FIXME: should be working..?
# - name: UFW / Enable service
#   service:
#     name: ufw
#     enabled: yes
#     state: started
#   when: '"qemu" not in group_names' # QEMU raspberry doesn't like this for some reason, not wasting time on this now, good luck future Seb (: