swagger: "2.0"
info:
  description: Custom Finance API By Seb
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /:
    get:
      operationId: "status.read"
      tags:
        - "Status"
      summary: "Status of the api endpoint"
      description: "Status of the api endpoint"
      responses:
        200:
          description: "Successful read of service status"
          schema:
            type: "object"
            properties:  
              peerberry:  
                type: "string"
              envestio:
                type: "string"
  /people:
    get:
      operationId: "people.read"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"