---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-claim
  namespace: monitoring
spec:
  storageClassName: hdd-na
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi