---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: prometheus
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
    scrape_configs:
    - job_name: prometheus
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - localhost:9090
    - job_name: qbittorent
      scrape_interval: 5s
      static_configs:
      - targets:
        - exporter-qbittorent:80
    - job_name: openvpn
      scrape_interval: 5s
      static_configs:
      - targets:
        - exporter-openvpn:80
    - job_name: traefik
      scrape_interval: 3s
      static_configs:
      - targets:
        - traefik-ingress-service.traefik:8082
    - job_name: traefik-online
      scrape_interval: 3s
      static_configs:
      - targets:
        - online-traefik-ingress-service.online:8082
    - job_name: 'bigraver-node'
      static_configs:
      - targets: ['10.8.0.1:9100']
    - job_name: 'raspi2-node'
      static_configs:
      - targets: ['10.8.0.10:9100']
    - job_name: 'carrot-node'
      static_configs:
      - targets: ['10.8.0.26:9100']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: monitoring-prometheus
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: monitoring-prometheus
    spec:
      containers:
      - name: prometheus
        ports:
        - containerPort: 9090
        image: prom/prometheus
        volumeMounts:
        - name: prometheus
          mountPath: /prometheus
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus
        persistentVolumeClaim:
          claimName: prometheus-claim
      - name: prometheus-config
        configMap:
          name: prometheus-config
          items:
          - key: prometheus.yml
            path: prometheus.yml
          defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-prometheus
  name: monitoring-prometheus
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 9090
  selector:
    k8s-app: monitoring-prometheus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: prometheus.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-prometheus
          servicePort: 80