---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-data-pv
  labels:
    contenttype: "torrent-data"
spec:
  capacity:
    storage: 2000Gi
  storageClassName: torrent-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd/na/torrent" # path to directory
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: torrent-config-pv
  labels:
    contenttype: "torrent-config"
spec:
  capacity:
    storage: 2Gi
  storageClassName: torrent-config
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/na/torrent-config" # path to directory
