---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-finance-pv
  labels:
    contenttype: "finance-db"
spec:
  capacity:
    storage: 30Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/finance/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - linux-wayne
