---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-varken-config
  namespace: monitoring
data:
  varken.ini: |-
    #!/bin/sh
    [global]
    sonarr_server_ids = 1
    tautulli_server_ids = false
    radarr_server_ids = false
    ombi_server_ids = false
    sickchill_server_ids = false
    unifi_server_ids = false

    [influxdb]
    url = monitoring-influxdb
    port = 80
    ssl = false
    verify_ssl = false
    username = bas
    password = Example1

    [tautulli-1]
    url = exporter-tautulli
    fallback_ip = 10.244.0.217
    apikey = a505364e63204fbb8c0f2018c15dd7bc
    ssl = false
    verify_ssl = false
    get_activity = true
    get_activity_run_seconds = 30
    get_stats = true
    get_stats_run_seconds = 3600

    [sonarr-1]
    url = sonarr.torrent:80
    apikey = d480869063d0470a8a2fa1d901c28352
    ssl = false
    verify_ssl = false
    missing_days = 7
    missing_days_run_seconds = 300
    future_days = 1
    future_days_run_seconds = 300
    queue = true
    queue_run_seconds = 300

    [sonarr-2]
    url = sonarr2.domain.tld:8989
    apikey = yyyyyyyyyyyyyyyy
    ssl = false
    verify_ssl = false
    missing_days = 7
    missing_days_run_seconds = 300
    future_days = 1
    future_days_run_seconds = 300
    queue = true
    queue_run_seconds = 300

    [radarr-1]
    url = radarr1.domain.tld
    apikey = xxxxxxxxxxxxxxxx
    ssl = false
    verify_ssl = false
    queue = true
    queue_run_seconds = 300
    get_missing = true
    get_missing_run_seconds = 300

    [radarr-2]
    url = radarr2.domain.tld
    apikey = yyyyyyyyyyyyyyyy
    ssl = false
    verify_ssl = false
    queue = true
    queue_run_seconds = 300
    get_missing = true
    get_missing_run_seconds = 300

    [ombi-1]
    url = ombi.domain.tld
    apikey = xxxxxxxxxxxxxxxx
    ssl = false
    verify_ssl = false
    get_request_type_counts = true
    request_type_run_seconds = 300
    get_request_total_counts = true
    request_total_run_seconds = 300
    get_issue_status_counts = true
    issue_status_run_seconds = 300

    [sickchill-1]
    url = sickchill.domain.tld:8081
    apikey = xxxxxxxxxxxxxxxx
    ssl = false
    verify_ssl = false
    get_missing = true
    get_missing_run_seconds = 300

    [unifi-1]
    url = unifi.domain.tld:8443
    username = ubnt
    password = ubnt
    site = default
    usg_name = MyRouter
    ssl = false
    verify_ssl = false
    get_usg_stats_run_seconds = 300
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exporter-varken
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: exporter-varken
    spec:
      containers:
      - name: exporter-varken
        image: boerderij/varken
        command: ["/bin/sh", "-c", "cp /app/data/varken.example.ini /config/varken.example.ini && cp /config-custom/varken.ini /config/varken.ini && chmod 777 /config/varken.ini && python3 /app/Varken.py --data-folder /config"]
        volumeMounts:
        - name: exporter-varken-config
          mountPath: /config-custom/varken.ini
          subPath: varken.ini
      volumes:
      - name: exporter-varken-config
        configMap:
          name: exporter-varken-config
          items:
          - key: varken.ini
            path: varken.ini
          defaultMode: 0777