---
apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-varken-config
  namespace: monitoring
data:
  varken.ini: |-
    #!/bin/sh
    [global]
    sonarr_server_ids = 1
    tautulli_server_ids = 1

    [influxdb]
    url = monitoring-influxdb
    port = 80
    ssl = false
    verify_ssl = false
    username = bas
    password = Example1

    [tautulli-1]
    url = exporter-tautulli
    port = 80
    apikey = a505364e63204fbb8c0f2018c15dd7bc
    ssl = false
    verify_ssl = false
    get_activity = true
    get_activity_run_seconds = 30
    get_stats = true
    get_stats_run_seconds = 3600

    [sonarr-1]
    url = sonarr.torrent:80
    apikey = d480869063d0470a8a2fa1d901c28352
    ssl = false
    verify_ssl = false
    missing_days = 7
    missing_days_run_seconds = 300
    future_days = 1
    future_days_run_seconds = 300
    queue = true
    queue_run_seconds = 300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-varken
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: exporter-varken
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: exporter-varken
    spec:
      containers:
      - name: exporter-varken
        image: boerderij/varken
        command: ["/bin/sh", "-c", "cp /app/data/varken.example.ini /config/varken.example.ini && cp /config-custom/varken.ini /config/varken.ini && chmod 777 /config/varken.ini && python3 /app/Varken.py --data-folder /config"]
        env:
        - name: DEBUG
          value: "False"
        volumeMounts:
        - name: exporter-varken-config
          mountPath: /config-custom/varken.ini
          subPath: varken.ini
      volumes:
      - name: exporter-varken-config
        configMap:
          name: exporter-varken-config
          items:
          - key: varken.ini
            path: varken.ini
          defaultMode: 0777