---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: plex-torrent-data-pv
  labels:
    contenttype: "plex-torrent-data"
spec:
  capacity:
    storage: 2000Gi
  storageClassName: plex-torrent-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd/na/torrent" # path to directory
