apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
spec:
  selector:
    app: immich-machine-learning
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
