apiVersion: v1
kind: Service
metadata:
  name: immich-server
spec:
  selector:
    app: immich-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: immich-server
  name: immich-server-lb
spec:
  ports:
  - name: http
    targetPort: 3001
    port: 80
  selector:
    app: immich-server
  loadBalancerIP: 192.168.6.77
  type: LoadBalancer

