apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - calico
  - cert-manager
  - metallb-system
  - dns
  - traefik
  - storage
  - online
  # - flux-system
  # - homeautomation
  # - kubernetes-dashboard
  # - monitoring
  - torrent
  - vpn
  - media
  - nextcloud
  - security
  - workflows
  - development
  - crm
