apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - calico
  - cert-manager
  - metallb-system
  - dns
  - traefik
  - storage
  - torrent
  - vpn
  - media
  - nextcloud
  - security
  - workflows
