---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: exporter-tautulli-pv
  labels:
    contenttype: "exporter-tautulli"
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/monitoring/tautulli
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - linux-wayne