---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: exporter-tautulli-claim
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "exporter-tautulli"
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter-tautulli
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: exporter-tautulli
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: exporter-tautulli
    spec:
      containers:
      - name: exporter-tautulli
        ports:
        - containerPort: 8181
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: linuxserver/tautulli
        volumeMounts:
          - name: tautulli
            mountPath: /config
      volumes:
        - name: tautulli
          persistentVolumeClaim:
            claimName: exporter-tautulli-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: exporter-tautulli
  name: exporter-tautulli
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8181
  selector:
    k8s-app: exporter-tautulli
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: exporter-tautulli
  namespace: monitoring
spec:
  rules:
  - host: tautulli.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: exporter-tautulli
          servicePort: 80