---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-claim
  namespace: torrent
spec:
  storageClassName: ssd-na
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-claim
  namespace: torrent
spec:
  storageClassName: jellyfin-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jellyfin-transcode-claim
#   namespace: torrent
# spec:
#   storageClassName: ssd-ha
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi