apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: service-toggle-app
  namespace: online
  files:
  - app.py
  - index.html
secretGenerator:
- name: service-toggle-auth
  namespace: online
  literals:
  - token=30QXXVsh5U4FVDEmpqcu64ONa1Y0StbShVskv7BEzXo=
resources:
- service-toggle.yml
- auth-middleware.yml
