---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vaultwarden-data-pv
  labels:
    contenttype: "vaultwarden-data"
spec:
  capacity:
    storage: 5Gi
  storageClassName: vaultwarden-data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/ha/vaultwarden/data"