---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-claim
spec:
  storageClassName: vaultwarden-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
