{
 "title": "OpenVPN",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OpenVPN</span>\n</div>"
  },
  {
   "title": "Connected OpenVPN clients",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openvpn_openvpn_server_connected_clients",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 2 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "openvpn_up",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Send / Received",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openvpn_server_client_sent_bytes_total) / sum(openvpn_server_client_received_bytes_total) \n",
     "legendFormat": "Total Received"
    }
   ]
  },
  {
   "title": "Send",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 6 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(openvpn_server_client_sent_bytes_total)",
     "legendFormat": "Total Received"
    }
   ]
  },
  {
   "title": "Received",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 8 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(openvpn_server_client_received_bytes_total)",
     "legendFormat": "Total Received"
    }
   ]
  }
 ]
}