# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: receiver
#   name: receiver
#   namespace: flux-system
# spec:
#   ports:
#   - name: http
#     targetPort: 9292
#     port: 80
#   selector:
#     app: notification-controller
#   loadBalancerIP: 192.168.6.81
#   type: ClusterIP

# kubectl -n flux-system get receiver/flux-system

# Since I'm using the annotation to trigger this, we don't really need to expose this further
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: generic
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: flux-system