{
 "title": "Start",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Node",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Rave Dashboard Start</span>\n</div>"
  },
  { "title": "Recently used", "type": "dashlist", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 } },
  { "title": "Cluster Health", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 3, "y": 2 } },
  { "title": "Apps", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 7, "y": 2 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Connected OpenVPN clients",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "openvpn_openvpn_server_connected_clients",
     "legendFormat": "Connected Clients"
    }
   ]
  },
  {
   "title": "Node Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$node:$port\",job=~\"$job\", chip=\"platform_coretemp_0\", sensor=\"temp2\"}",
     "legendFormat": "Core 1"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$node:$port\",job=~\"$job\", chip=\"platform_coretemp_0\", sensor=\"temp3\"}",
     "legendFormat": "Core 2"
    },
    {
     "expr": "node_hwmon_fan_rpm{instance=~\"$node:$port\",job=~\"$job\",chip=\"platform_it87_656\", sensor=\"fan1\"}",
     "legendFormat": "Fan 1"
    },
    {
     "expr": "node_hwmon_fan_rpm{instance=~\"$node:$port\",job=~\"$job\",chip=\"platform_it87_656\", sensor=\"fan2\"}",
     "legendFormat": "Fan 2"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "type": "vonage-status-panel",
   "gridPos": { "h": 1, "w": 2, "x": 14, "y": 4 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "openvpn_up",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "content": "<div class=\"text-center\">\n  <h4>Cluster Resources</h4>\n</div>\n\n",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "RAM Usage / Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"container_name\"   !~ /kubepods.*/ AND \"container_name\"   !~ /system.slice.*/ AND \"container_name\"   !~ /user.slice.*/  ) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "!=", "value": "kubepods/besteffort" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage Rate / Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"container_name\"   !~ /kubepods.*/ AND \"container_name\"   !~ /system.slice.*/ AND \"container_name\"   !~ /user.slice.*/  ) AND $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "!=", "value": "kubepods/besteffort" }
     ]
    }
   ]
  },
  {
   "title": "Big-Raver Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=~\"bigraver-node\",device!~'rootfs', mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}} - Available"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=~\"bigraver-node\",device!~'rootfs', mountpoint=\"/mnt/largehdd\"}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  },
  {
   "title": "Raspi2 Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=~\"raspi2-node\",device!~'rootfs', mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}} - Available"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=~\"raspi2-node\",device!~'rootfs', mountpoint=\"/mnt/largehdd\"}",
     "legendFormat": "{{mountpoint}} - Available"
    }
   ]
  }
 ]
}