---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: argo-artifacts-pv
  labels:
    contenttype: "argo-artifacts"
spec:
  capacity:
    storage: 5Gi
  storageClassName: argo-artifacts
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/na/argo/artifacts"