---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-artifacts-claim
spec:
  storageClassName: argo-artifacts
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi