---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: torrent
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      volumes:
        - name: bazarr-config-volume
          persistentVolumeClaim:
            claimName: bazarr-config-claim
        - name: bazarr-torrent-volume
          persistentVolumeClaim:
            claimName: torrent-data-claim
      containers:
      - name: bazarr
        resources:
        image: linuxserver/bazarr
        ports:
        - name: http
          containerPort: 6767
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: bazarr-torrent-volume
            mountPath: /downloads
          - name: bazarr-config-volume
            mountPath: /config
        #   - name: bazarr-config-volume
        #     mountPath: /config/bazarr/bazarr.conf
        #     subPath: bazarr.conf
        #   - name: set-goose-config-volume
        #     mountPath: /goose/set-goose.sh
        #     subPath: set-goose.sh
        #   - name: set-goose-ovpn-volume
        #     mountPath: /etc/openvpn/ro-10.conf
        #     subPath: ro-10.conf
        #   - name: goose-credentials-volume
        #     mountPath: /goose/login.conf
        #     subPath: login.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bazarr
  name: bazarr
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 6767
    port: 80
  selector:
    app: bazarr
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarringress
  namespace: torrent
spec:
  rules:
  - host: bazarr.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr-lb-service
  namespace: torrent
spec:
  ports:
  - name: http
    port: 80
    targetPort: 6767
  selector:
    app: bazarr
  type: LoadBalancer
  loadBalancerIP: 192.168.6.64



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr-bas
  namespace: torrent
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: bazarr-bas-tls
  commonName: bazarr.bas
  dnsNames:
  - bazarr.bas
  - www.bazarr.bas
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-non-tls
  namespace: torrent
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`bazarr.bas`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: bazarr
      port: 80
    middlewares:
    - name: http-redirect-to-https
      namespace: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-tls
  namespace: torrent
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`bazarr.bas`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: bazarr
      port: 80
  tls:
    secretName: bazarr-bas-tls