---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["networking","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints/status"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: dns
spec:
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      
      volumes:
      - name: etcd-pki
        secret:
          secretName: hostetcd
          defaultMode: 0744
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: la1r.workload/essential
                operator: In
                values:
                - "true"
      containers:
      - name: external-dns
        resources:
        image: k8s.gcr.io/external-dns/external-dns:v0.13.1
        # command: ["sleep", "10000000"]
        command: ["/bin/sh"]
        args:
        - -c
        - >
          ETCD_URLS=https://$(HOST_IP):2379
          /bin/external-dns
          --source=ingress
          --source=service
          --always-publish-not-ready-addresses
          --provider=coredns
          --log-level=debug
        # - --dry-run # debug only
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        # - name: ETCD_URLS
        #   value: "https://192.168.5.3:2379"
        - name: ETCD_CA_FILE
          value: "/etc/kubernetes/pki/etcd/ca.crt"
        - name: ETCD_CERT_FILE
          value: "/etc/kubernetes/pki/etcd/server.crt"
        - name: ETCD_KEY_FILE
          value: "/etc/kubernetes/pki/etcd/server.key"
        volumeMounts:
          - name: etcd-pki
            mountPath: "/etc/kubernetes/pki/etcd"