---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-claim
  namespace: analytics
spec:
  storageClassName: nfs-112
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi