apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
    # sablier.enable: "false"
    # sablier.group: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
          
      # Essential
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: la1r.workload/essential
                operator: In
                values:
                - "true"
      priorityClassName: essential

      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - name: api
              containerPort: 9000
            - name: webui
              containerPort: 9001
          env:
            - name: MINIO_BROWSER_REDIRECT_URL 
              value: https://minio.bas
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
            - name: MINIO_ROOT_USER
              value: basraven
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: webui
      protocol: TCP
      port: 80
      targetPort: 9001
  type: ClusterIP

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-bas
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: minio-bas-tls
  commonName: minio.bas
  dnsNames:
  - minio.bas
  - www.minio.bas
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-https
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    # traefik.ingress.kubernetes.io/router.middlewares: "traefik-sablier-llm@kubernetescrd"
spec:
  tls:
  - secretName: minio-bas-tls
  rules:
  - host: minio.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 80
  - host: api.minio.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9000
