---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: homeassistant-config-pv
  labels:
    contenttype: "homeassistant-config"
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largessd/configs/homeassistant
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver