---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeautomation
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: serial-by-id
          hostPath:
            path: /dev/serial/by-id
            type: Directory
        - name: homeassistant-config-volume
          persistentVolumeClaim:
            claimName: homeassistant-config-claim
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 8123
        env:
        - name: TZ
          value: Europe/Amsterdam
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: serial-by-id
          mountPath: /dev/serial/by-id
          readOnly: true
        - name: homeassistant-config-volume
          mountPath: /config

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeautomation
  labels:
    app: homeassistant
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
  - name: http
    port: 8123
    targetPort: 8123

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homeassistant-bas
  namespace: homeautomation
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: homeassistant-bas-tls
  commonName: homeassistant.bas
  dnsNames:
  - homeassistant.bas
  - www.homeassistant.bas

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-https
  namespace: homeautomation
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  tls:
  - secretName: homeassistant-bas-tls
  rules:
  - host: homeassistant.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
