apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeautomation
resources:
- homeautomation-priority.yml
- pv
- homeassistant.yml
- zigbee2mqtt.yml
- mqtt.yml
- otbr.yml
- matter-server.yml

