---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-config-claim
  namespace: homeautomation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: camera-settings-data
  selector:
    matchLabels:
      contenttype: "camera-settings-data"
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-data-claim
  namespace: homeautomation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: camera-data
  selector:
    matchLabels:
      contenttype: "camera-data"
  resources:
    requests:
      storage: 50Gi