---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data-claim
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ssd-na
  resources:
    requests:
      storage: 20Gi