---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
    - name: Check if packages are installed
      apt: name={{item}} state=present
      with_items:
          - samba
    # - name: Add "{{ target_user }}" to www-data 
    #   user:
    #     name: "{{ target_user }}"
    #     shell: /bin/bash
    #     groups: www-data
    #     append: yes
    - name: smb config
      template: src=smb.conf.j2 dest=/etc/samba/smb.conf mode=0755
    - name: Restart service dnsmasq, in all cases
      service:
        name: smbd
        state: restarted
    - name: Include samba credentials
      include_vars:
        file: "{{credentials_dir}}/samba/samba-credentials.yaml"
    - name: set Samba passwords for each user
      shell: "printf '{{ item.passwd }}\n{{ item.passwd }}\n' | smbpasswd -a {{ item.name }}"
      with_items:
      - "{{ samba_users }}"
      tags: smbpasswd