---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chronograf-claim
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "chronograf"
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  namespace: monitoring
  labels:
    app: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: chronograf
        app: chronograf
    spec:
      containers:
      - name: chronograf
        ports:
        - containerPort: 8888
        image: chronograf
        volumeMounts:
          - name: chronograf
            mountPath: /var/lib/chronograf
      volumes:
        - name: chronograf
          persistentVolumeClaim:
            claimName: chronograf-claim
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: chronograf
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chronograf
  namespace: monitoring
spec:
  rules:
  - host: chronograf.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: chronograf
          servicePort: 80