---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly3-data-claim
  namespace: accounting
spec:
  storageClassName: firefly3-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly3-database-claim
  namespace: accounting
spec:
  storageClassName: firefly3-database
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
