# ---
# Source:   https://www.digitalocean.com/community/tutorials/how-to-set-up-an-elasticsearch-fluentd-and-kibana-efk-logging-stack-on-kubernetes
# Source 2: https://blog.ptrk.io/how-to-deploy-an-efk-stack-to-kubernetes/
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: elasticsearch-claim
#   namespace: efk
# spec:
#   accessModes:
#   - ReadWriteMany 
#   storageClassName: local-storage
#   selector:
#     matchLabels:
#       contenttype: "elasticsearch"
#   resources:
#     requests:
#       storage: 200Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: elasticsearch-config-claim-local
#   namespace: efk
# spec:
#   accessModes:
#   - ReadWriteMany 
#   storageClassName: local-storage
#   selector:
#     matchLabels:
#       contenttype: "elasticsearch-config-local"
#   resources:
#     requests:
#       storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
  template:
    metadata:
      labels:
        task: efk
        k8s-app: elasticsearch
    spec:
      volumes:
      - name: elasticsearch-data-volume
        persistentVolumeClaim:
          claimName: elasticsearch-data-claim
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "1536Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9200 
        - name: integration
          containerPort: 9300 
        volumeMounts:
        - name: elasticsearch-data-volume
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_USERNAME
          value: "admin"
        - name: ELASTIC_PASSWORD
          value: "admin"
        - name: http.cors.enabled
          value: "true"
        - name: http.cors.allow-origin
          value:  "*"
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        image: elasticsearch:7.9.1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: efk
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9200
  - name: interface
    port: 9200
    targetPort: 9200
  - name: integration
    port: 9300
    targetPort: 9300
  selector:
    k8s-app: elasticsearch
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearchingress
  namespace: monitoring
spec:
  rules:
  - host: es.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch
            port:
              number: 80