---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-config-claim
  namespace: analytics
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi