apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: weekly-grafana-cloud-backup
spec:
  schedule: "35 12 * * 0" # Every Sunday at 12:00 AM
  timezone: "Europe/Amsterdam"
  workflowSpec:
    workflowTemplateRef:
      name: essential-cloud-backup
    arguments:
      parameters:
        - name: localpath
          value: "/mnt/ssd/na/grafana"
