apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: weekly-remote-cube-backup
spec:
  schedule: "40 8 * * 0" # Every Sunday at 12:40 AM
  concurrencyPolicy: "Forbid"
  timezone: "Europe/Amsterdam"
  workflowSpec:
    workflowTemplateRef:
      name: remote-cube-backup
    arguments:
      parameters:
        - name: backupServer
          value: "basraven@10.8.0.4"
