---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-web-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany 
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "web"
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data-claim
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteMany  
  storageClassName: local-storage
  selector:
    matchLabels:
      contenttype: "data"
  resources:
    requests:
      storage: 800Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
      - name: set-nextcloud-volume
        configMap:
          name: set-nextcloud
          items:
          - key: set-nextcloud.sh
            path: set-nextcloud.sh
          defaultMode: 0744
      - name: apcu-config-volume
        configMap:
          name: apcu-config
          items:
          - key: apcu.config.php
            path: apcu.config.php
          defaultMode: 0744
      - name: nextcloud-web
        persistentVolumeClaim:
          claimName: nextcloud-web-claim
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-claim
      containers:
      - name: nextcloud
        image: nextcloud
        command:
          - "/set-nextcloud/set-nextcloud.sh"
        ports:
        - containerPort: 80
        env:
        - name: NEXTCLOUD_TABLE_PREFIX
          value: ""
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: MYSQL_HOST
          value: "mariadb"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadbsecret
              key: password
        volumeMounts:
          - name: nextcloud-web
            mountPath: "/var/www/html"
          - name: nextcloud-data
            mountPath: "/var/www/html/data"
          - name: set-nextcloud-volume
            mountPath: /set-nextcloud
          # - name: apcu-config-volume
          #   mountPath: /var/www/html/config
          #   subPath: apcu.config.php
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nextcloud
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloudingress-raafbox
  namespace: nextcloud
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: raafbox.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloudingress
  namespace: nextcloud
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: cloud.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80