---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-state-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-data-claim
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi