---
- name: "cpu power savings / install cpufrequtils and tlp"
  become: yes
  apt:
    name: 
    - cpufrequtils
    - tlp
    state: present

- name: "cpu power savings / set CPU governor to power-saving"
  become: yes
  shell: cpufreq-set -g powersave
  
  # TODO: automate
- name: "cpu power savings / start TLP"
  become: yes
  shell: tlp start