---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strimzi-claim
  namespace: my-kafka-project
spec:
  storageClassName: nfs-212
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi