---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-config-claim
  namespace: dns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-212
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-dnsmasq-claim
  namespace: dns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-212
  resources:
    requests:
      storage: 5Gi