---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient-la1r
  namespace: online
  labels:
    app: ddclient-la1r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddclient-la1r
  template:
    metadata:
      labels:
        app: ddclient-la1r
    spec:
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: cache
          emptyDir: {}
      containers:
      - name: ddclient-la1r
        image: linuxserver/ddclient
        command: ["/bin/sh"]
        args:
          - -c
          - |
            # Create config file directly with printf
            cat > /config/ddclient.conf << EOF
            daemon=300
            syslog=yes
            # mail=root
            # mail-failure=root
            pid=/var/run/ddclient.pid
            cache=/tmp/ddclient.cache
            ssl=yes

            # Use web service to get external IP
            use=web
            web=ipecho.net/plain
            web-skip=''
            
            # Namecheap configuration
            protocol=namecheap
            server=dynamicdns.park-your-domain.com
            login=la1r.com
            password=$DDNS_PASSWORD
            @,*,vpn,status
            EOF
            # Start ddclient
            exec /init
        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: cache
            mountPath: /tmp
        env:
          - name: DDNS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ddnspasword
                key: DDNS_PASSWORD