---
- name: Init K8s
  shell: |
    kubeadm init --pod-network-cidr="{{kubernetes_cidr}}" \
    --ignore-preflight-errors=all \
    --apiserver-advertise-address="{{ ansible_default_ipv4.address }}"
  args:
    executable: /bin/bash
  async: 600
  poll: 5

        