---
- name: Init Kubernetes / Init Kubernetes
  become: yes
  shell: |
    kubeadm init --pod-network-cidr="{{kubernetes_cidr}}" \
    --ignore-preflight-errors=all \
    --apiserver-advertise-address="{{ ansible_default_ipv4.address }}"
  args:
    executable: /bin/bash
  async: 600
  poll: 5

- name: "Init Kubernetes / Copy kubeconfig to {{ target_user_name }} home directory"
  become: yes
  shell: |
    mkdir -p ~/.kube
    cp -f /etc/kubernetes/admin.conf ~/.kube/config
    chown -f "{{ target_user_name }}:{{ target_user_name }}" ~/.kube/config
  args:
    executable: /bin/bash
        