---
- name: Install on Common / Remove swap and unmount
  become: yes
  shell: |
    swapoff -a
    mount -a
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Install on Common / Install kubelet, kubeadm and kubernetes-cni
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - kubelet
    - kubeadm
    - kubernetes-cni

- name: Install on Common / Sysctl config updates
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^{{item}} ='
    line: "{{item}} = 1"
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
    
- name: Install on Common / tempfix for ipv4
  become: yes
  shell: |
    echo '1' > {{item}}
  args:
    executable: /bin/bash
  with_items:
    - /proc/sys/net/bridge/bridge-nf-call-iptables
    - /proc/sys/net/ipv4/ip_forward