---
- name: Install on Common / Remove swap and unmount
  become: yes
  shell: |
    swapoff -a
    mount -a
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Install on Common / Install kubelet, kubeadm and kubernetes-cni
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - kubelet
    - kubeadm
    - kubernetes-cni

- name: Install on Common / Bridge NF Call ip4
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.bridge.bridge-nf-call-iptables ='
    line: net.bridge.bridge-nf-call-iptables = 1

- name: Install on Common / Bridge NF Call ip6
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.bridge.bridge-nf-call-ip6tables ='
    line: net.bridge.bridge-nf-call-ip6tables = 1
    
    
- name: Install on Common / tempfix for ipv4
  become: yes
  shell: |
    echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  args:
    executable: /bin/bash