---
- name: Install on Raspbian / Remove swap 1/6
  command: swapoff -a
  ignore_errors: yes
- name: Install on Raspbian / Remove swap 2/6
  command: systemctl disable dphys-swapfile
  ignore_errors: yes
- name: Install on Raspbian / Remove swap 3/6
  command: apt-get remove dphys-swapfile -y
  ignore_errors: yes


- name: Install on Raspbian / Remove swap 4/6
  command: dphys-swapfile swapoff
  ignore_errors: yes
  become: yes
- name: Install on Raspbian / Remove swap 5/6
  command: dphys-swapfile uninstall
  ignore_errors: yes
  become: yes
- name: Install on Raspbian / Remove swap 6/6
  command: update-rc.d dphys-swapfile remove
  ignore_errors: yes
  become: yes

- name: Install on Raspbian / Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    validate_certs: no
  become: yes
- name: Install on Raspbian / Add kubernetes key to repo
  apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
  become: yes

- name: Install on Raspbian / Update apt-get
  command: apt-get update -q 
  become: yes

- name: Install on Raspbian / Install kubeadm
  command: apt-get install -yq kubeadm
  become: yes


- name: Install on Raspbian / copy /boot/cmdline.txt
  copy:
    src: /boot/cmdline.txt
    dest: /root/cmdline-backup-{{ansible_date_time.date}}-{{ansible_date_time.time}}.txt
    remote_src: yes
  become: yes
- name: Install on Raspbian / Ugly fix for /boot/cmdline.txt
  lineinfile:
      path: /boot/cmdline.txt
      backrefs: yes
      regexp: '^(.*rootwait)\s+$'
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
  become: yes


- name: Install on Raspbian / Reboot the host to reload the changed config
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting the host to reload the changed config'
  async: 15
  poll: 5
  ignore_errors: yes
  become: yes

- name: Install on Raspbian / Wait for system to become reachable again
  wait_for_connection:
      delay: 30
      timeout: 10

# - name: "new method: kubeadm config images pull"
#   shell:  'kubeadm config images pull'
#   args:
#     executable: /bin/bash

# - name: Install on Raspbian / "allow kubernetes through ufw"
#   shell:  'ufw allow 6443'
#   args:
#     executable: /bin/bash
#   become: yes
  
# - name: Install on Raspbian / Adding existing user '{{ target_user_name }}' to group docker
#   user:
#     name: '{{ target_user_name }}'
#     groups: docker
#     append: yes
#   become: yes