---
- name: Join Kubernetes / Include k8s join token
  include_vars:
    file: "{{credentials_dir}}/kubernetes/join-token.yaml"

- name: Join Kubernetes / Join K8s
  command: kubeadm join {{kubernetes_master}}:6443 --token {{k8s_join_token}} --discovery-token-unsafe-skip-ca-verification --ignore-preflight-errors=all
  ignore_errors: yes
  async: 600
  poll: 5

  