---
- include: install-kubernetes.yml
  tags:
    - kubernetes_server
- include: networking.yml
  tags:
    - kubernetes_server
- include: install-storage-prereq.yml
  tags:
    - storage_kubernetes
  when: ansible_lsb.id != "Raspbian"
    
# - include: init-kubernetes.yml
#   tags:
#     - init_kubernetes
# - include: fetch-kubeconfig.yml
#   tags:
#     - fetch_kubernetes
# - include: join-kubernetes.yml
#   tags:
#     - join_kubernetes
# - include: reset-kubernetes.yml
#   tags:
#     - reset_kubernetes