---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  namespace: maintenance
  labels:
    app: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      volumes:
        - name: chronograf
          emptyDir: {}
      containers:
      - name: chronograf
        image: chronograf
        ports:
        - name: http
          containerPort: 8888
        volumeMounts:
        - name: chronograf
          mountPath: /var/lib/chronograf
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf-service
  namespace: maintenance
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: chronograf
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-chronograf-ingress
  namespace: maintenance
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: influxdb.bas
    http:
      paths:
      - path: /
        backend:
          serviceName: chronograf-service
          servicePort: 80