---
- include: install-openvpn.yml
  tags:
    - openvpn_client  
    - openvpn_server  
- include: prepare-folders.yml
  tags:
    - openvpn_server  
- include: create-server.yml
  tags:
    - openvpn_server  
- include: install-iptables-persistent.yml
  tags:
    - openvpn_server  
- include: setup-client.yml
  tags:
    - openvpn_client
- include: create-user.yml
  tags: 
    - create_ovpn_user
- include: delete-user.yml
  tags: 
    - delete_ovpn_user
