---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
  namespace: monitoring
spec:
  storageClassName: hdd-ha
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi