---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-backup-script
  namespace: backup
data:
  ha-backup.sh: |-
    #!/bin/sh
    apk add rsync
    rsync -a -z --no-perms --no-owner --no-group --delete --force --update --progress /ha/* /ha-mirror
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ha-backup
  namespace: backup
  labels:
    app: ha-backup
spec:
  schedule: "5 2 * * 0"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ha-backup
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution :
                nodeSelectorTerms:
                - matchExpressions:
                  - key: la1r.storage/111
                    operator: In
                    values: [ "true" ]
          restartPolicy: Never    
          volumes:
          - name: ha-data-volume
            persistentVolumeClaim:
            nfs: 
              server: 192.168.5.100
              path: /mnt/hdd/ha
          - name: ha-data-mirror-volume
            nfs: 
              server: 192.168.5.1
              path: /mnt/hdd/ha
          - name: ha-backup-script-volume
            configMap:
              name: ha-backup-script
              items:
              - key: ha-backup.sh
                path: ha-backup.sh
              defaultMode: 0744
          containers:
          - name: ha-backup
            image: alpine:latest
            resources:
              limits:
                memory: "2048Mi"
                cpu: "1500m"
            command: 
              - /ha-backup-script/ha-backup.sh
            volumeMounts:
              - name: ha-data-volume
                mountPath: /ha
              - name: ha-data-mirror-volume
                mountPath: /ha-mirror
              - name: ha-backup-script-volume
                mountPath: /ha-backup-script
   