---
samba_shares:

  media_shares:
    - name: "basraven"
      comment: "Media Bas"
      path: "/mnt/hdd/media/bas"
    - name: "stephanie"
      comment: "Media Stephanie"
      path: "/mnt/hdd/media/stephanie"
    - name: "gezin"
      comment: "Media Gezin"
      path: "/mnt/hdd/media/gezin"


  special_write_shares:
    - name: "torrent"
      comment: "Torrent"
      path: "/mnt/hdd/torrent"
    - name: "windowsbackup"
      comment: "Windows Backup"
      path: "/mnt/hdd/windowsbackup"
    - name: "staging"
      comment: "Staging folder"
      path: "/mnt/hdd/staging"

  backup_shares:
    - name: "hdd-media"
      comment: "Backup - Media"
      path: "/mnt/hdd/media"
    - name: "hdd-na"
      comment: "Backup - hdd-na"
      path: "/mnt/hdd/na"
    - name: "hdd-ha"
      comment: "Backup - hdd-ha"
      path: "/mnt/hdd/ha"
    - name: "ssd-na"
      comment: "Backup - ssd-na"
      path: "/mnt/ssd/na"
    - name: "ssd-ha"
      comment: "Backup - ssd-ha"
      path: "/mnt/ssd/ha"
