# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.define "ubuntu" do |web|
    web.vm.box = "packer/.builds/ubuntu-20.04.hyperv.box"
    
    # Remove attempts to use samba
    config.vm.synced_folder '.', '/vagrant', disabled: true
    
    config.vm.provider "hyperv" do |v|
      v.memory = 2056
      v.cpus = 2
    end
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
    config.vm.network "public_network", bridge: "Standardswitch"
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL
  end
  # config.vm.define "centos" do |web|
  #   web.vm.box = "packer/.builds/ubuntu-20.04.hyperv.box"
    
  #   # Remove attempts to use samba
  #   config.vm.synced_folder '.', '/vagrant', disabled: true

  #   config.vm.provider "hyperv" do |v|
  #     v.memory = 2056
  #     v.cpus = 2
  #   end
  #   if Vagrant.has_plugin?("vagrant-vbguest")
  #     config.vbguest.auto_update = false
  #   end
  #   config.vm.network "public_network", bridge: "Standardswitch"
  #   config.vm.provision "shell", inline: <<-SHELL
  #     apt-get update
  #     apt-get install -y apache2
  #   SHELL
  # end
end
