---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-plex
  name: kube-plex
  namespace: torrent
spec:
  ports:
  - name: http
    port: 32400
    nodePort: 32400
  selector:
    app: kube-plex
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plexingress-custom
  namespace: torrent
  # annotations:
  #   kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: plex.thuis
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-plex
          servicePort: 32400