---
- hosts: all
  remote_user: pi
  tasks:
    - name: Add the user '{{target_user}}' with a specific uid and a primary group of 'sudo'
      user:
        name: "{{target_user}}"
        shell: /bin/bash
        groups: sudo,adm,dialout,cdrom,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
        append: yes
    - name: Add {{ target_user }} user to the sudoers
      copy:
          dest: "/etc/sudoers.d/{{ target_user }}"
          content: "{{ target_user }}  ALL=(ALL)  NOPASSWD: ALL"
    - name: Set authorized key took from file
      authorized_key:
        user: "{{target_user}}"
        key: "{{ lookup('file', '/credentials/ssh/id_rsa.pub') }}"
        state: present
