apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  labels:
    app: immich-machine-learning
    sablier.enable: "true"
    sablier.group: immich
spec:
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      # NonEssential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/nonessential
                operator: In
                values:
                - "true"
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:release
        ports:
          - containerPort: 3003
        volumeMounts:
        - name: model-cache
          mountPath: /cache
        # envFrom:
        # - configMapRef:
        #     name: env-config
      volumes:
      - name: model-cache
        emptyDir: {}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: immich-machine-learning
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: immich-machine-learning
  minReplicas: 1
  maxReplicas: 1
