FROM php:7.0-apache
RUN apt-get update && \
    apt-get install -y libapache2-mod-php7.0 php7.0-gd php7.0-json php7.0-mysql php7.0-curl php7.0-mbstring && \
    apt-get install -y php7.0-intl php7.0-mcrypt php-imagick php7.0-xml php7.0-zip