---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-script
  namespace: finance
data:
  aggregator-daily.sh: |-
    #!/bin/sh
    apt-get update
    apt-get install git -y
    git clone https://github.com/basraven/finagg.git finagg
    cd finagg 
    pip3 install -r requirements.txt
    python3 aggregate.py
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aggregator-daily
  namespace: finance
  labels:
    app: aggregator-daily
spec:
  schedule: "5 4 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aggregator
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - linux-wayne
          restartPolicy: Never    
          volumes:
          - name: aggregator-script-volume
            configMap:
              name: aggregator-script
              items:
              - key: aggregator-daily.sh
                path: aggregator-daily.sh
              defaultMode: 0744
          containers:
          - name: aggregator-peerberry
            image: python:3-slim
            env:
            - name: TOKEN
              value: peerberry
            volumeMounts:
              - name: aggregator-script-volume
                mountPath: /aggregator-script
            command: 
              - /aggregator-script/aggregator-daily.sh
          - name: aggregator-fastinvest
            image: python:3-slim
            env:
            - name: TOKEN
              value: fastinvest
            volumeMounts:
              - name: aggregator-script-volume
                mountPath: /aggregator-script
            command: 
              - /aggregator-script/aggregator-daily.sh