---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-claim
  namespace: registry
spec:
  storageClassName: registry-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
